# Método da aceitação-rejeição

**Exercícios**

**1.** Gere variáveis aleatórias com distribuição exponencial
$Exp(\lambda = 1)$ usando o método da aceitação-rejeição. Use uma função
de proposta uniforme no intervalo [0, 5] e visualize o histograma das
amostras geradas.

**2.** Gere variáveis aleatórias com distribuição normal $N(0,1)$ usando
uma distribuição proposta Cauchy padrão $C(0,1)$. Gere 1000 amostras e
compare com a densidade da distribuição normal padrão.

**3.** Use o método da aceitação-rejeição para gerar amostras de uma
variável Beta $B(2, 3)$. Use uma distribuição proposta uniforme
$U(0, 1)$.

**4.** Use o método de aceitação-rejeição para gerar variáveis
aleatórias $X \sim \Gamma(3, 2)$ usando uma distribuição proposta
exponencial $Exp(2)$.

**5.** Use o método da aceitação-rejeição para gerar variáveis
aleatórias Log-Normais $X \sim \text{LogNormal}(0, 1)$ usando uma
distribuição proposta normal $N(0, 1)$.

**6.** Use o método da aceitação-rejeição para gerar variáveis Weibull
$W(1, 2)$ usando uma distribuição proposta exponencial.