<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 16 Manipulação de dados | Introdução ao R e Simulação</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 16 Manipulação de dados | Introdução ao R e Simulação" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/docs/ciencias.png" />
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 16 Manipulação de dados | Introdução ao R e Simulação" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="twitter:image" content="/docs/ciencias.png" />

<meta name="author" content="Renato de Paula" />


<meta name="date" content="2025-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="gráficos-r-base.html"/>
<link rel="next" href="o-pacote-ggplot2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Laboratório de Estatistica I</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="01-intro.html"><a href="#pref%C3%A1cio"><i class="fa fa-check"></i><b>1</b> Prefácio</a></li>
<li class="chapter" data-level="2" data-path="normas-de-funcionamento.html"><a href="normas-de-funcionamento.html"><i class="fa fa-check"></i><b>2</b> Normas de Funcionamento</a>
<ul>
<li class="chapter" data-level="2.1" data-path="01-intro.html"><a href="#avalia%C3%A7%C3%A3o-cont%C3%ADnua-e-acesso-%C3%A0s-%C3%A9pocas-de-exame"><i class="fa fa-check"></i><b>2.1</b> Avaliação Contínua e Acesso às Épocas de Exame</a></li>
<li class="chapter" data-level="2.2" data-path="01-intro.html"><a href="#condi%C3%A7%C3%B5es-para-que-os-testes-contribuam-para-aprova%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>2.2</b> Condições para que os testes contribuam para aprovação</a></li>
<li class="chapter" data-level="2.3" data-path="01-intro.html"><a href="#exemplos-de-situa%C3%A7%C3%B5es-poss%C3%ADveis"><i class="fa fa-check"></i><b>2.3</b> Exemplos de situações possíveis</a></li>
<li class="chapter" data-level="2.4" data-path="normas-de-funcionamento.html"><a href="normas-de-funcionamento.html#notas-importantes"><i class="fa fa-check"></i><b>2.4</b> Notas importantes</a></li>
<li class="chapter" data-level="2.5" data-path="normas-de-funcionamento.html"><a href="normas-de-funcionamento.html#datas-importantes"><i class="fa fa-check"></i><b>2.5</b> Datas importantes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-e-rstudio.html"><a href="r-e-rstudio.html"><i class="fa fa-check"></i><b>3</b> R e RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="01-intro.html"><a href="#instala%C3%A7%C3%A3o-e-funcionalidades-b%C3%A1sicas"><i class="fa fa-check"></i><b>3.1</b> Instalação e funcionalidades básicas</a></li>
<li class="chapter" data-level="3.2" data-path="r-e-rstudio.html"><a href="r-e-rstudio.html#navegar-no-rstudio"><i class="fa fa-check"></i><b>3.2</b> Navegar no RStudio</a></li>
<li class="chapter" data-level="3.3" data-path="r-e-rstudio.html"><a href="r-e-rstudio.html#atalhos"><i class="fa fa-check"></i><b>3.3</b> Atalhos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="01-intro.html"><a href="#r-como-calculadora-e-opera%C3%A7%C3%B5es-aritm%C3%A9ticas"><i class="fa fa-check"></i><b>4</b> R como Calculadora e Operações Aritméticas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="r-como-calculadora-e-operações-aritméticas.html"><a href="r-como-calculadora-e-operações-aritméticas.html"><i class="fa fa-check"></i><b>4.1</b> O Prompt do R</a></li>
<li class="chapter" data-level="4.2" data-path="01-intro.html"><a href="#objetos-e-vari%C3%A1veis"><i class="fa fa-check"></i><b>4.2</b> Objetos e Variáveis</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="01-intro.html"><a href="#o-que-%C3%A9-uma-vari%C3%A1vel"><i class="fa fa-check"></i><b>4.2.1</b> O que é uma Variável?</a></li>
<li class="chapter" data-level="4.2.2" data-path="01-intro.html"><a href="#atribui%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>4.2.2</b> Atribuições</a></li>
<li class="chapter" data-level="4.2.3" data-path="01-intro.html"><a href="#regras-para-defini%C3%A7%C3%A3o-de-vari%C3%A1veis"><i class="fa fa-check"></i><b>4.2.3</b> Regras para definição de variáveis</a></li>
<li class="chapter" data-level="4.2.4" data-path="r-como-calculadora-e-operações-aritméticas.html"><a href="r-como-calculadora-e-operações-aritméticas.html#tipos-de-dados"><i class="fa fa-check"></i><b>4.2.4</b> Tipos de Dados</a></li>
<li class="chapter" data-level="4.2.5" data-path="r-como-calculadora-e-operações-aritméticas.html"><a href="r-como-calculadora-e-operações-aritméticas.html#comandos-importantes"><i class="fa fa-check"></i><b>4.2.5</b> Comandos Importantes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="01-intro.html"><a href="#operadores-aritm%C3%A9ticos-em-r"><i class="fa fa-check"></i><b>4.3</b> Operadores Aritméticos em R</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="01-intro.html"><a href="#controle-da-quantidade-de-d%C3%ADgitos-mostrados"><i class="fa fa-check"></i><b>4.3.1</b> Controle da Quantidade de Dígitos Mostrados</a></li>
<li class="chapter" data-level="4.3.2" data-path="r-como-calculadora-e-operações-aritméticas.html"><a href="r-como-calculadora-e-operações-aritméticas.html#objetos-predefinidos-infinito-indefinido-e-valores-ausentes"><i class="fa fa-check"></i><b>4.3.2</b> Objetos Predefinidos, Infinito, Indefinido e Valores Ausentes</a></li>
<li class="chapter" data-level="4.3.3" data-path="01-intro.html"><a href="#lidando-com-nan-e-na-em-opera%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>4.3.3</b> Lidando com NaN e NA em Operações</a></li>
<li class="chapter" data-level="4.3.4" data-path="01-intro.html"><a href="#fun%C3%A7%C3%B5es-%C3%BAteis-para-detectar-nan-e-na"><i class="fa fa-check"></i><b>4.3.4</b> Funções Úteis para Detectar NaN e NA</a></li>
<li class="chapter" data-level="4.3.5" data-path="01-intro.html"><a href="#tipagem-din%C3%A2mica-em-r"><i class="fa fa-check"></i><b>4.3.5</b> Tipagem Dinâmica em R</a></li>
<li class="chapter" data-level="4.3.6" data-path="01-intro.html"><a href="#convers%C3%A3o-entre-tipos-de-dados"><i class="fa fa-check"></i><b>4.3.6</b> Conversão entre Tipos de Dados</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="01-intro.html"><a href="#fun%C3%A7%C3%B5es-print-readline-paste-e-cat"><i class="fa fa-check"></i><b>4.4</b> Funções <code>print()</code>, <code>readline()</code>, <code>paste()</code> e <code>cat()</code></a></li>
<li class="chapter" data-level="4.5" data-path="01-intro.html"><a href="#operadores-l%C3%B3gicos-e-relacionais"><i class="fa fa-check"></i><b>4.5</b> Operadores Lógicos e Relacionais</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="01-intro.html"><a href="#operadores-l%C3%B3gicos"><i class="fa fa-check"></i><b>4.5.1</b> Operadores Lógicos</a></li>
<li class="chapter" data-level="4.5.2" data-path="r-como-calculadora-e-operações-aritméticas.html"><a href="r-como-calculadora-e-operações-aritméticas.html#operadores-relacionais"><i class="fa fa-check"></i><b>4.5.2</b> Operadores Relacionais</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="01-intro.html"><a href="#exerc%C3%ADcios"><i class="fa fa-check"></i><b>4.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="01-intro.html"><a href="#estrutura-de-dados-b%C3%A1sicas"><i class="fa fa-check"></i><b>5</b> Estrutura de Dados Básicas</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html"><i class="fa fa-check"></i><b>5.1</b> Vetor</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#tipos-comuns-de-vetores"><i class="fa fa-check"></i><b>5.1.1</b> Tipos Comuns de Vetores</a></li>
<li class="chapter" data-level="5.1.2" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#construindo-vetores"><i class="fa fa-check"></i><b>5.1.2</b> Construindo Vetores</a></li>
<li class="chapter" data-level="5.1.3" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#acesso-a-elementos-de-um-vetor"><i class="fa fa-check"></i><b>5.1.3</b> Acesso a Elementos de um Vetor</a></li>
<li class="chapter" data-level="5.1.4" data-path="01-intro.html"><a href="#fun%C3%A7%C3%B5es-comuns-para-vetores"><i class="fa fa-check"></i><b>5.1.4</b> Funções Comuns para Vetores</a></li>
<li class="chapter" data-level="5.1.5" data-path="01-intro.html"><a href="#opera%C3%A7%C3%B5es-com-vetores"><i class="fa fa-check"></i><b>5.1.5</b> Operações com Vetores</a></li>
<li class="chapter" data-level="5.1.6" data-path="01-intro.html"><a href="#exerc%C3%ADcios-1"><i class="fa fa-check"></i><b>5.1.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#fatores"><i class="fa fa-check"></i><b>5.2</b> Fatores</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="01-intro.html"><a href="#manipula%C3%A7%C3%A3o-de-fatores"><i class="fa fa-check"></i><b>5.2.1</b> Manipulação de Fatores</a></li>
<li class="chapter" data-level="5.2.2" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#gerando-fatores-com-gl"><i class="fa fa-check"></i><b>5.2.2</b> Gerando Fatores com <code>gl()</code></a></li>
<li class="chapter" data-level="5.2.3" data-path="01-intro.html"><a href="#exerc%C3%ADcios-2"><i class="fa fa-check"></i><b>5.2.3</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#matriz-e-array"><i class="fa fa-check"></i><b>5.3</b> Matriz e Array</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#criando-matrizes"><i class="fa fa-check"></i><b>5.3.1</b> Criando matrizes</a></li>
<li class="chapter" data-level="5.3.2" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#construindo-matrizes"><i class="fa fa-check"></i><b>5.3.2</b> Construindo Matrizes</a></li>
<li class="chapter" data-level="5.3.3" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#acessar-elementos-de-uma-matriz"><i class="fa fa-check"></i><b>5.3.3</b> Acessar Elementos de uma Matriz</a></li>
<li class="chapter" data-level="5.3.4" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#nomear-linhas-e-colunas-de-uma-matriz"><i class="fa fa-check"></i><b>5.3.4</b> Nomear Linhas e Colunas de uma Matriz</a></li>
<li class="chapter" data-level="5.3.5" data-path="01-intro.html"><a href="#multiplica%C3%A7%C3%A3o-de-matrizes"><i class="fa fa-check"></i><b>5.3.5</b> Multiplicação de matrizes</a></li>
<li class="chapter" data-level="5.3.6" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#adicionar-linhas-e-colunas-a-uma-matriz"><i class="fa fa-check"></i><b>5.3.6</b> Adicionar Linhas e Colunas a uma Matriz</a></li>
<li class="chapter" data-level="5.3.7" data-path="01-intro.html"><a href="#algumas-outras-fun%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>5.3.7</b> Algumas outras funções</a></li>
<li class="chapter" data-level="5.3.8" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#criando-um-array"><i class="fa fa-check"></i><b>5.3.8</b> Criando um array</a></li>
<li class="chapter" data-level="5.3.9" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#acessar-elementos-de-um-array"><i class="fa fa-check"></i><b>5.3.9</b> Acessar Elementos de um array</a></li>
<li class="chapter" data-level="5.3.10" data-path="01-intro.html"><a href="#exerc%C3%ADcios-3"><i class="fa fa-check"></i><b>5.3.10</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#data-frame"><i class="fa fa-check"></i><b>5.4</b> Data Frame</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#criar-um-data-frame"><i class="fa fa-check"></i><b>5.4.1</b> Criar um Data Frame</a></li>
<li class="chapter" data-level="5.4.2" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#aceder-a-colunas"><i class="fa fa-check"></i><b>5.4.2</b> Aceder a Colunas</a></li>
<li class="chapter" data-level="5.4.3" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#aceder-a-linhas"><i class="fa fa-check"></i><b>5.4.3</b> Aceder a Linhas</a></li>
<li class="chapter" data-level="5.4.4" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#adicionar-e-remover-colunas"><i class="fa fa-check"></i><b>5.4.4</b> Adicionar e Remover Colunas</a></li>
<li class="chapter" data-level="5.4.5" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#fundir-data-frames"><i class="fa fa-check"></i><b>5.4.5</b> Fundir Data Frames</a></li>
<li class="chapter" data-level="5.4.6" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#explorar-o-data-frame"><i class="fa fa-check"></i><b>5.4.6</b> Explorar o Data Frame</a></li>
<li class="chapter" data-level="5.4.7" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#filtragem-condicional-num-data.frame"><i class="fa fa-check"></i><b>5.4.7</b> Filtragem condicional num <code>data.frame</code></a></li>
<li class="chapter" data-level="5.4.8" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-summary"><i class="fa fa-check"></i><b>5.4.8</b> A Função <code>summary()</code></a></li>
<li class="chapter" data-level="5.4.9" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#valores-ausentes"><i class="fa fa-check"></i><b>5.4.9</b> Valores ausentes</a></li>
<li class="chapter" data-level="5.4.10" data-path="01-intro.html"><a href="#exerc%C3%ADcios-4"><i class="fa fa-check"></i><b>5.4.10</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#listas"><i class="fa fa-check"></i><b>5.5</b> Listas</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="estrutura-de-dados-básicas.html"><a href="estrutura-de-dados-básicas.html#criar-e-manipular-listas"><i class="fa fa-check"></i><b>5.5.1</b> Criar e Manipular Listas</a></li>
<li class="chapter" data-level="5.5.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-5"><i class="fa fa-check"></i><b>5.5.2</b> Exercícios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="01-intro.html"><a href="#estruturas-de-sele%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>6</b> Estruturas de Seleção</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estruturas-de-seleção.html"><a href="estruturas-de-seleção.html"><i class="fa fa-check"></i><b>6.1</b> Condicional <code>if</code></a></li>
<li class="chapter" data-level="6.2" data-path="estruturas-de-seleção.html"><a href="estruturas-de-seleção.html#estrutura-if...else"><i class="fa fa-check"></i><b>6.2</b> Estrutura <code>if...else</code></a></li>
<li class="chapter" data-level="6.3" data-path="estruturas-de-seleção.html"><a href="estruturas-de-seleção.html#condicional-else-if"><i class="fa fa-check"></i><b>6.3</b> Condicional <code>else if</code></a></li>
<li class="chapter" data-level="6.4" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-ifelse"><i class="fa fa-check"></i><b>6.4</b> A função <code>ifelse()</code></a></li>
<li class="chapter" data-level="6.5" data-path="estruturas-de-seleção.html"><a href="estruturas-de-seleção.html#exemplos"><i class="fa fa-check"></i><b>6.5</b> Exemplos</a></li>
<li class="chapter" data-level="6.6" data-path="01-intro.html"><a href="#exerc%C3%ADcios-6"><i class="fa fa-check"></i><b>6.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="01-intro.html"><a href="#fun%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>7</b> Funções</a>
<ul>
<li class="chapter" data-level="7.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-7"><i class="fa fa-check"></i><b>7.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="scripts-em-r.html"><a href="scripts-em-r.html"><i class="fa fa-check"></i><b>8</b> Scripts em R</a>
<ul>
<li class="chapter" data-level="8.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-8"><i class="fa fa-check"></i><b>8.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="leitura-de-dados.html"><a href="leitura-de-dados.html"><i class="fa fa-check"></i><b>9</b> Leitura de dados</a>
<ul>
<li class="chapter" data-level="9.1" data-path="leitura-de-dados.html"><a href="leitura-de-dados.html#leitura-de-dados-da-entrada-do-utilizador"><i class="fa fa-check"></i><b>9.1</b> Leitura de Dados da Entrada do Utilizador</a></li>
<li class="chapter" data-level="9.2" data-path="01-intro.html"><a href="#diret%C3%B3rio-de-trabalho"><i class="fa fa-check"></i><b>9.2</b> Diretório de trabalho</a></li>
<li class="chapter" data-level="9.3" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-read.table"><i class="fa fa-check"></i><b>9.3</b> A Função <code>read.table()</code></a></li>
<li class="chapter" data-level="9.4" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-read.csv"><i class="fa fa-check"></i><b>9.4</b> A função <code>read.csv()</code></a></li>
<li class="chapter" data-level="9.5" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-read.csv2"><i class="fa fa-check"></i><b>9.5</b> A função <code>read.csv2()</code></a></li>
<li class="chapter" data-level="9.6" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-read_excel"><i class="fa fa-check"></i><b>9.6</b> A Função <code>read_excel()</code></a></li>
<li class="chapter" data-level="9.7" data-path="leitura-de-dados.html"><a href="leitura-de-dados.html#leitura-de-dados-online"><i class="fa fa-check"></i><b>9.7</b> Leitura de Dados Online</a></li>
<li class="chapter" data-level="9.8" data-path="01-intro.html"><a href="#exerc%C3%ADcios-9"><i class="fa fa-check"></i><b>9.8</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="pipe.html"><a href="pipe.html"><i class="fa fa-check"></i><b>10</b> Pipe</a>
<ul>
<li class="chapter" data-level="10.1" data-path="pipe.html"><a href="pipe.html#o-operador-pipe"><i class="fa fa-check"></i><b>10.1</b> O operador pipe</a></li>
<li class="chapter" data-level="10.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-10"><i class="fa fa-check"></i><b>10.2</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="loop-while.html"><a href="loop-while.html"><i class="fa fa-check"></i><b>11</b> Loop while</a>
<ul>
<li class="chapter" data-level="11.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-11"><i class="fa fa-check"></i><b>11.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="loop-for.html"><a href="loop-for.html"><i class="fa fa-check"></i><b>12</b> Loop for</a>
<ul>
<li class="chapter" data-level="12.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-12"><i class="fa fa-check"></i><b>12.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="01-intro.html"><a href="#fam%C3%ADlia-xapply"><i class="fa fa-check"></i><b>13</b> Família <code>Xapply()</code></a>
<ul>
<li class="chapter" data-level="13.1" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-apply"><i class="fa fa-check"></i><b>13.1</b> Função <code>apply()</code></a></li>
<li class="chapter" data-level="13.2" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-lapply"><i class="fa fa-check"></i><b>13.2</b> Função <code>lapply()</code></a></li>
<li class="chapter" data-level="13.3" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-sapply"><i class="fa fa-check"></i><b>13.3</b> Função <code>sapply()</code></a></li>
<li class="chapter" data-level="13.4" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-tapply"><i class="fa fa-check"></i><b>13.4</b> Função <code>tapply()</code></a></li>
<li class="chapter" data-level="13.5" data-path="01-intro.html"><a href="#exerc%C3%ADcios-13"><i class="fa fa-check"></i><b>13.5</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="01-intro.html"><a href="#exerc%C3%ADcios-de-revis%C3%A3o"><i class="fa fa-check"></i><b>14</b> Exercícios de Revisão</a></li>
<li class="chapter" data-level="15" data-path="01-intro.html"><a href="#gr%C3%A1ficos-r-base"><i class="fa fa-check"></i><b>15</b> Gráficos (R base)</a>
<ul>
<li class="chapter" data-level="15.1" data-path="01-intro.html"><a href="#gr%C3%A1fico-de-barras"><i class="fa fa-check"></i><b>15.1</b> Gráfico de Barras</a></li>
<li class="chapter" data-level="15.2" data-path="01-intro.html"><a href="#gr%C3%A1fico-circular-pizza"><i class="fa fa-check"></i><b>15.2</b> Gráfico Circular (Pizza)</a></li>
<li class="chapter" data-level="15.3" data-path="gráficos-r-base.html"><a href="gráficos-r-base.html"><i class="fa fa-check"></i><b>15.3</b> Histograma</a></li>
<li class="chapter" data-level="15.4" data-path="gráficos-r-base.html"><a href="gráficos-r-base.html#box-plot"><i class="fa fa-check"></i><b>15.4</b> Box-plot</a></li>
<li class="chapter" data-level="15.5" data-path="01-intro.html"><a href="#gr%C3%A1fico-de-dispers%C3%A3o"><i class="fa fa-check"></i><b>15.5</b> Gráfico de Dispersão</a></li>
<li class="chapter" data-level="15.6" data-path="01-intro.html"><a href="#gr%C3%A1fico-de-linhas"><i class="fa fa-check"></i><b>15.6</b> Gráfico de Linhas</a></li>
<li class="chapter" data-level="15.7" data-path="01-intro.html"><a href="#exerc%C3%ADcios-14"><i class="fa fa-check"></i><b>15.7</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="01-intro.html"><a href="#manipula%C3%A7%C3%A3o-de-dados"><i class="fa fa-check"></i><b>16</b> Manipulação de dados</a>
<ul>
<li class="chapter" data-level="16.1" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html"><i class="fa fa-check"></i><b>16.1</b> Tibbles</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#criar-e-trabalhar-com-tibbles"><i class="fa fa-check"></i><b>16.1.1</b> Criar e trabalhar com Tibbles</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="01-intro.html"><a href="#manipula%C3%A7%C3%A3o-de-dados-com-dplyr"><i class="fa fa-check"></i><b>16.2</b> Manipulação de Dados com <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="01-intro.html"><a href="#sele%C3%A7%C3%A3o-de-colunas-com-select"><i class="fa fa-check"></i><b>16.2.1</b> Seleção de Colunas com <code>select()</code></a></li>
<li class="chapter" data-level="16.2.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-15"><i class="fa fa-check"></i><b>16.2.2</b> Exercícios</a></li>
<li class="chapter" data-level="16.2.3" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#ordenando-a-base-de-dados"><i class="fa fa-check"></i><b>16.2.3</b> Ordenando a Base de Dados</a></li>
<li class="chapter" data-level="16.2.4" data-path="01-intro.html"><a href="#exerc%C3%ADcios-16"><i class="fa fa-check"></i><b>16.2.4</b> Exercícios</a></li>
<li class="chapter" data-level="16.2.5" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#filtrando-linhas-da-base-de-dados"><i class="fa fa-check"></i><b>16.2.5</b> Filtrando Linhas da Base de Dados</a></li>
<li class="chapter" data-level="16.2.6" data-path="01-intro.html"><a href="#exerc%C3%ADcios-17"><i class="fa fa-check"></i><b>16.2.6</b> Exercícios</a></li>
<li class="chapter" data-level="16.2.7" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#modificar-e-criar-novas-colunas"><i class="fa fa-check"></i><b>16.2.7</b> Modificar e criar novas colunas</a></li>
<li class="chapter" data-level="16.2.8" data-path="01-intro.html"><a href="#exerc%C3%ADcios-18"><i class="fa fa-check"></i><b>16.2.8</b> Exercícios</a></li>
<li class="chapter" data-level="16.2.9" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#sumarizar-a-base-de-dados"><i class="fa fa-check"></i><b>16.2.9</b> Sumarizar a Base de Dados</a></li>
<li class="chapter" data-level="16.2.10" data-path="01-intro.html"><a href="#exer%C3%ADcios"><i class="fa fa-check"></i><b>16.2.10</b> Exerícios</a></li>
<li class="chapter" data-level="16.2.11" data-path="manipulação-de-dados.html"><a href="manipulação-de-dados.html#juntando-tabelas-em-r-com-dplyr"><i class="fa fa-check"></i><b>16.2.11</b> Juntando Tabelas em R com dplyr</a></li>
<li class="chapter" data-level="16.2.12" data-path="01-intro.html"><a href="#exerc%C3%ADcios-19"><i class="fa fa-check"></i><b>16.2.12</b> Exercícios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="o-pacote-ggplot2.html"><a href="o-pacote-ggplot2.html"><i class="fa fa-check"></i><b>17</b> O pacote <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="17.1" data-path="01-intro.html"><a href="#a-gram%C3%A1tica-dos-gr%C3%A1ficos"><i class="fa fa-check"></i><b>17.1</b> A Gramática dos Gráficos</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="01-intro.html"><a href="#estrutura-b%C3%A1sica"><i class="fa fa-check"></i><b>17.1.1</b> Estrutura básica</a></li>
<li class="chapter" data-level="17.1.2" data-path="01-intro.html"><a href="#exemplos-pr%C3%A1ticos"><i class="fa fa-check"></i><b>17.1.2</b> Exemplos práticos</a></li>
<li class="chapter" data-level="17.1.3" data-path="01-intro.html"><a href="#boas-pr%C3%A1ticas"><i class="fa fa-check"></i><b>17.1.3</b> Boas práticas</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-20"><i class="fa fa-check"></i><b>17.2</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-sample"><i class="fa fa-check"></i><b>18</b> A função <code>sample()</code></a>
<ul>
<li class="chapter" data-level="18.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-21"><i class="fa fa-check"></i><b>18.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="01-intro.html"><a href="#probabilidade-e-vari%C3%A1veis-aleat%C3%B3rias"><i class="fa fa-check"></i><b>19</b> Probabilidade e Variáveis Aleatórias</a>
<ul>
<li class="chapter" data-level="19.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-22"><i class="fa fa-check"></i><b>19.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="01-intro.html"><a href="#simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>20</b> Simulação</a>
<ul>
<li class="chapter" data-level="20.1" data-path="01-intro.html"><a href="#simula%C3%A7%C3%A3o-e-gera%C3%A7%C3%A3o-de-n%C3%BAmeros-pseudoaleat%C3%B3rios"><i class="fa fa-check"></i><b>20.1</b> Simulação e Geração de Números Pseudoaleatórios</a></li>
<li class="chapter" data-level="20.2" data-path="01-intro.html"><a href="#a-fun%C3%A7%C3%A3o-set.seed"><i class="fa fa-check"></i><b>20.2</b> A função <code>set.seed()</code></a></li>
<li class="chapter" data-level="20.3" data-path="01-intro.html"><a href="#exerc%C3%ADcios-23"><i class="fa fa-check"></i><b>20.3</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%B5es-de-probabilidade"><i class="fa fa-check"></i><b>21</b> Distribuições de Probabilidade</a>
<ul>
<li class="chapter" data-level="21.1" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica"><i class="fa fa-check"></i><b>21.1</b> Função de distribuição empírica</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica-no-r-fun%C3%A7%C3%A3o-ecdf"><i class="fa fa-check"></i><b>21.1.1</b> Função de distribuição empírica no R, função <code>ecdf()</code></a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-uniforme-discreta"><i class="fa fa-check"></i><b>21.2</b> Distribuição Uniforme Discreta</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-24"><i class="fa fa-check"></i><b>21.2.1</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-de-bernoulli"><i class="fa fa-check"></i><b>21.3</b> Distribuição de Bernoulli</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades"><i class="fa fa-check"></i><b>21.3.1</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.3.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-25"><i class="fa fa-check"></i><b>21.3.2</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-binomial"><i class="fa fa-check"></i><b>21.4</b> Distribuição Binomial</a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades-1"><i class="fa fa-check"></i><b>21.4.1</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.4.2" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-massa-de-probabilidade-te%C3%B3rica"><i class="fa fa-check"></i><b>21.4.2</b> Função massa de probabilidade (teórica)</a></li>
<li class="chapter" data-level="21.4.3" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-massa-de-probabilidade-simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>21.4.3</b> Função massa de probabilidade (simulação)</a></li>
<li class="chapter" data-level="21.4.4" data-path="01-intro.html"><a href="#compara%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>21.4.4</b> Comparação</a></li>
<li class="chapter" data-level="21.4.5" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>21.4.5</b> Função de distribuição</a></li>
<li class="chapter" data-level="21.4.6" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica-1"><i class="fa fa-check"></i><b>21.4.6</b> Função de distribuição empírica</a></li>
<li class="chapter" data-level="21.4.7" data-path="01-intro.html"><a href="#exerc%C3%ADcios-26"><i class="fa fa-check"></i><b>21.4.7</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-geom%C3%A9trica"><i class="fa fa-check"></i><b>21.5</b> Distribuição Geométrica</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades-2"><i class="fa fa-check"></i><b>21.5.1</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.5.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-27"><i class="fa fa-check"></i><b>21.5.2</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-de-poisson"><i class="fa fa-check"></i><b>21.6</b> Distribuição de Poisson</a>
<ul>
<li class="chapter" data-level="21.6.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades-3"><i class="fa fa-check"></i><b>21.6.1</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.6.2" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-massa-de-probabilidade-te%C3%B3rica-1"><i class="fa fa-check"></i><b>21.6.2</b> Função massa de probabilidade (teórica)</a></li>
<li class="chapter" data-level="21.6.3" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-massa-de-probabilidade-simula%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>21.6.3</b> Função massa de probabilidade (simulação)</a></li>
<li class="chapter" data-level="21.6.4" data-path="01-intro.html"><a href="#compara%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>21.6.4</b> Comparação</a></li>
<li class="chapter" data-level="21.6.5" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>21.6.5</b> Função de distribuição</a></li>
<li class="chapter" data-level="21.6.6" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica-2"><i class="fa fa-check"></i><b>21.6.6</b> Função de distribuição empírica</a></li>
<li class="chapter" data-level="21.6.7" data-path="01-intro.html"><a href="#exerc%C3%ADcios-28"><i class="fa fa-check"></i><b>21.6.7</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-uniforme-cont%C3%ADnua"><i class="fa fa-check"></i><b>21.7</b> Distribuição Uniforme Contínua</a>
<ul>
<li class="chapter" data-level="21.7.1" data-path="01-intro.html"><a href="#nota%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>21.7.1</b> Notação</a></li>
<li class="chapter" data-level="21.7.2" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades-4"><i class="fa fa-check"></i><b>21.7.2</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.7.3" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-densidade-de-probabilidade"><i class="fa fa-check"></i><b>21.7.3</b> Função densidade de probabilidade</a></li>
<li class="chapter" data-level="21.7.4" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-densidade-de-probabilidade-simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>21.7.4</b> Função densidade de probabilidade (simulação)</a></li>
<li class="chapter" data-level="21.7.5" data-path="01-intro.html"><a href="#compara%C3%A7%C3%A3o-2"><i class="fa fa-check"></i><b>21.7.5</b> Comparação</a></li>
<li class="chapter" data-level="21.7.6" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-2"><i class="fa fa-check"></i><b>21.7.6</b> Função de distribuição</a></li>
<li class="chapter" data-level="21.7.7" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica-3"><i class="fa fa-check"></i><b>21.7.7</b> Função de distribuição empírica</a></li>
<li class="chapter" data-level="21.7.8" data-path="01-intro.html"><a href="#exerc%C3%ADcios-29"><i class="fa fa-check"></i><b>21.7.8</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.8" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-exponencial"><i class="fa fa-check"></i><b>21.8</b> Distribuição Exponencial</a>
<ul>
<li class="chapter" data-level="21.8.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-probabilidades-5"><i class="fa fa-check"></i><b>21.8.1</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="21.8.2" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-densidade-de-probabilidade-te%C3%B3rica"><i class="fa fa-check"></i><b>21.8.2</b> Função densidade de probabilidade (teórica)</a></li>
<li class="chapter" data-level="21.8.3" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-densidade-de-probabilidade-simula%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>21.8.3</b> Função densidade de probabilidade (simulação)</a></li>
<li class="chapter" data-level="21.8.4" data-path="01-intro.html"><a href="#compara%C3%A7%C3%A3o-3"><i class="fa fa-check"></i><b>21.8.4</b> Comparação</a></li>
<li class="chapter" data-level="21.8.5" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-3"><i class="fa fa-check"></i><b>21.8.5</b> Função de distribuição</a></li>
<li class="chapter" data-level="21.8.6" data-path="01-intro.html"><a href="#fun%C3%A7%C3%A3o-de-distribui%C3%A7%C3%A3o-emp%C3%ADrica-4"><i class="fa fa-check"></i><b>21.8.6</b> Função de distribuição empírica</a></li>
<li class="chapter" data-level="21.8.7" data-path="01-intro.html"><a href="#exerc%C3%ADcios-30"><i class="fa fa-check"></i><b>21.8.7</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="21.9" data-path="01-intro.html"><a href="#distribui%C3%A7%C3%A3o-normal"><i class="fa fa-check"></i><b>21.9</b> Distribuição Normal</a>
<ul>
<li class="chapter" data-level="21.9.1" data-path="01-intro.html"><a href="#exerc%C3%ADcios-31"><i class="fa fa-check"></i><b>21.9.1</b> Exercícios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="01-intro.html"><a href="#exerc%C3%ADcios-extra"><i class="fa fa-check"></i><b>22</b> Exercícios extra</a></li>
<li class="chapter" data-level="23" data-path="01-intro.html"><a href="#m%C3%A9todo-da-transformada-inversa"><i class="fa fa-check"></i><b>23</b> Método da transformada inversa</a>
<ul>
<li class="chapter" data-level="23.1" data-path="01-intro.html"><a href="#vari%C3%A1vel-aleat%C3%B3ria-discreta"><i class="fa fa-check"></i><b>23.1</b> Variável aleatória discreta</a></li>
<li class="chapter" data-level="23.2" data-path="01-intro.html"><a href="#exerc%C3%ADcios-32"><i class="fa fa-check"></i><b>23.2</b> Exercícios</a></li>
<li class="chapter" data-level="23.3" data-path="01-intro.html"><a href="#vari%C3%A1vel-aleat%C3%B3ria-cont%C3%ADnua"><i class="fa fa-check"></i><b>23.3</b> Variável aleatória contínua</a></li>
<li class="chapter" data-level="23.4" data-path="01-intro.html"><a href="#exerc%C3%ADcios-33"><i class="fa fa-check"></i><b>23.4</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="01-intro.html"><a href="#m%C3%A9todo-da-aceita%C3%A7%C3%A3o-rejei%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>24</b> Método da aceitação-rejeição</a></li>
<li class="chapter" data-level="25" data-path="teoremas-limites.html"><a href="teoremas-limites.html"><i class="fa fa-check"></i><b>25</b> Teoremas limites</a>
<ul>
<li class="chapter" data-level="25.1" data-path="01-intro.html"><a href="#lei-fraca-dos-grandes-n%C3%BAmeros"><i class="fa fa-check"></i><b>25.1</b> Lei fraca dos grandes números</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="01-intro.html"><a href="#usando-n%C3%BAmeros-aleat%C3%B3rios-para-o-c%C3%A1lculo-de-integrais"><i class="fa fa-check"></i><b>26</b> Usando números aleatórios para o cálculo de Integrais</a>
<ul>
<li class="chapter" data-level="26.1" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-int_abgx-dx"><i class="fa fa-check"></i><b>26.1</b> Cálculo de <span class="math inline">\(\int_{a}^{b}g(x)\, dx\)</span></a></li>
<li class="chapter" data-level="26.2" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-int_0inftygx-dx"><i class="fa fa-check"></i><b>26.2</b> Cálculo de <span class="math inline">\(\int_{0}^{\infty}g(x)\, dx\)</span></a></li>
<li class="chapter" data-level="26.3" data-path="01-intro.html"><a href="#c%C3%A1lculo-de-integrais-multidimensionais"><i class="fa fa-check"></i><b>26.3</b> Cálculo de integrais multidimensionais</a></li>
<li class="chapter" data-level="26.4" data-path="01-intro.html"><a href="#exerc%C3%ADcios-34"><i class="fa fa-check"></i><b>26.4</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="01-intro.html"><a href="#relat%C3%B3rios"><i class="fa fa-check"></i><b>27</b> Relatórios</a>
<ul>
<li class="chapter" data-level="27.1" data-path="relatórios.html"><a href="relatórios.html"><i class="fa fa-check"></i><b>27.1</b> Markdown</a>
<ul>
<li class="chapter" data-level="27.1.1" data-path="01-intro.html"><a href="#%C3%AAnfase"><i class="fa fa-check"></i><b>27.1.1</b> Ênfase</a></li>
<li class="chapter" data-level="27.1.2" data-path="01-intro.html"><a href="#t%C3%ADtulos"><i class="fa fa-check"></i><b>27.1.2</b> Títulos</a></li>
<li class="chapter" data-level="27.1.3" data-path="relatórios.html"><a href="relatórios.html#listas-1"><i class="fa fa-check"></i><b>27.1.3</b> Listas</a></li>
<li class="chapter" data-level="27.1.4" data-path="01-intro.html"><a href="#equa%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>27.1.4</b> Equações</a></li>
<li class="chapter" data-level="27.1.5" data-path="01-intro.html"><a href="#c%C3%B3digo"><i class="fa fa-check"></i><b>27.1.5</b> Código</a></li>
<li class="chapter" data-level="27.1.6" data-path="relatórios.html"><a href="relatórios.html#links"><i class="fa fa-check"></i><b>27.1.6</b> Links</a></li>
<li class="chapter" data-level="27.1.7" data-path="relatórios.html"><a href="relatórios.html#imagens"><i class="fa fa-check"></i><b>27.1.7</b> Imagens</a></li>
<li class="chapter" data-level="27.1.8" data-path="relatórios.html"><a href="relatórios.html#tabelas"><i class="fa fa-check"></i><b>27.1.8</b> Tabelas</a></li>
</ul></li>
<li class="chapter" data-level="27.2" data-path="relatórios.html"><a href="relatórios.html#r-markdown"><i class="fa fa-check"></i><b>27.2</b> R Markdown</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="relatórios.html"><a href="relatórios.html#criando-um-arquivo-.rmd"><i class="fa fa-check"></i><b>27.2.1</b> Criando um arquivo <code>.Rmd</code></a></li>
<li class="chapter" data-level="27.2.2" data-path="relatórios.html"><a href="relatórios.html#estrutura-do-arquivo-r-markdown"><i class="fa fa-check"></i><b>27.2.2</b> Estrutura do arquivo R Markdown</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="28" data-path="01-intro.html"><a href="#refer%C3%AAncias"><i class="fa fa-check"></i><b>28</b> Referências</a></li>
<li class="chapter" data-level="29" data-path="respostas.html"><a href="respostas.html"><i class="fa fa-check"></i><b>29</b> Respostas</a>
<ul>
<li class="chapter" data-level="29.1" data-path="respostas.html"><a href="respostas.html#o-pacote-dplyr"><i class="fa fa-check"></i><b>29.1</b> O pacote dplyr</a>
<ul>
<li class="chapter" data-level="29.1.1" data-path="respostas.html"><a href="respostas.html#selecionando-colunas"><i class="fa fa-check"></i><b>29.1.1</b> Selecionando colunas</a></li>
<li class="chapter" data-level="29.1.2" data-path="respostas.html"><a href="respostas.html#ordenando-a-base"><i class="fa fa-check"></i><b>29.1.2</b> Ordenando a base</a></li>
<li class="chapter" data-level="29.1.3" data-path="respostas.html"><a href="respostas.html#filtrando-linhas"><i class="fa fa-check"></i><b>29.1.3</b> Filtrando linhas</a></li>
<li class="chapter" data-level="29.1.4" data-path="respostas.html"><a href="respostas.html#modificando-e-criando-novas-colunas"><i class="fa fa-check"></i><b>29.1.4</b> Modificando e criando novas colunas</a></li>
<li class="chapter" data-level="29.1.5" data-path="respostas.html"><a href="respostas.html#sumarizando-a-base"><i class="fa fa-check"></i><b>29.1.5</b> Sumarizando a base</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introdução ao R e Simulação</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="manipulação-de-dados" class="section level1 hasAnchor" number="16">
<h1><span class="header-section-number">Capítulo 16</span> Manipulação de dados<a href="#manipula%C3%A7%C3%A3o-de-dados" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="tibbles" class="section level2 hasAnchor" number="16.1">
<h2><span class="header-section-number">16.1</span> Tibbles<a href="manipulação-de-dados.html#tibbles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Tibbles</strong> são uma versão moderna e melhorada dos data frames em R,
introduzida pelo pacote <code>tibble</code>, que faz parte do <code>tidyverse</code> — um
conjunto de pacotes desenvolvido para facilitar a ciência de dados em R.
Os tibbles foram projetados para ultrapassar algumas das limitações dos
data frames tradicionais, oferecendo uma estrutura de dados mais robusta
e intuitiva para manipulação e análise de dados.</p>
<p><strong>Diferenças Principais entre Tibble e Data Frame</strong></p>
<p>Os tibbles têm várias vantagens em relação aos data frames,
especialmente em termos de usabilidade e integração com o <code>tidyverse</code>. A
tabela abaixo resume as principais diferenças:</p>
<table>
<colgroup>
<col width="25%" />
<col width="30%" />
<col width="44%" />
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Data Frame</th>
<th>Tibble</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Impressão no Console</td>
<td>Exibe todos os dados</td>
<td>Exibe um resumo com 10 linhas e colunas visíveis</td>
</tr>
<tr class="even">
<td>Conversão de Strings</td>
<td>Converte strings para fatores por padrão</td>
<td>Mantém strings como caracteres</td>
</tr>
<tr class="odd">
<td>Manuseio de Colunas</td>
<td>Apenas vetores, listas podem ser problemáticas</td>
<td>Permite listas, funções, outros tibbles</td>
</tr>
<tr class="even">
<td>Nomes de Colunas</td>
<td>Nomes devem ser únicos e sem espaços</td>
<td>Nomes podem ter espaços, ser duplicados, etc.</td>
</tr>
<tr class="odd">
<td>Retorno de Subsetting (<code>[</code>)</td>
<td>Pode retornar um vetor ou data frame</td>
<td>Sempre retorna um tibble</td>
</tr>
<tr class="even">
<td>Compatibilidade e Integração</td>
<td>Totalmente compatível com base R</td>
<td>Compatível, mas otimizado para uso com tidyverse</td>
</tr>
<tr class="odd">
<td>Manipulação de Dados</td>
<td>Menos intuitivo para algumas operações.</td>
<td>Mais intuitivo e fácil de usar, especialmente com operações encadeadas.</td>
</tr>
</tbody>
</table>
<div id="criar-e-trabalhar-com-tibbles" class="section level3 hasAnchor" number="16.1.1">
<h3><span class="header-section-number">16.1.1</span> Criar e trabalhar com Tibbles<a href="manipulação-de-dados.html#criar-e-trabalhar-com-tibbles" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Criar um <code>tibble</code> é semelhante a criar um data frame, mas com uma
sintaxe ligeiramente diferente que facilita a criação de colunas
complexas.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="manipulação-de-dados.html#cb213-1" tabindex="-1"></a><span class="co"># Carregar o pacote tibble</span></span>
<span id="cb213-2"><a href="manipulação-de-dados.html#cb213-2" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb213-3"><a href="manipulação-de-dados.html#cb213-3" tabindex="-1"></a></span>
<span id="cb213-4"><a href="manipulação-de-dados.html#cb213-4" tabindex="-1"></a><span class="co"># Criando um tibble</span></span>
<span id="cb213-5"><a href="manipulação-de-dados.html#cb213-5" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb213-6"><a href="manipulação-de-dados.html#cb213-6" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb213-7"><a href="manipulação-de-dados.html#cb213-7" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span>),</span>
<span id="cb213-8"><a href="manipulação-de-dados.html#cb213-8" tabindex="-1"></a>  <span class="at">z =</span> x <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb213-9"><a href="manipulação-de-dados.html#cb213-9" tabindex="-1"></a>)</span>
<span id="cb213-10"><a href="manipulação-de-dados.html#cb213-10" tabindex="-1"></a></span>
<span id="cb213-11"><a href="manipulação-de-dados.html#cb213-11" tabindex="-1"></a><span class="fu">print</span>(tb)</span>
<span id="cb213-12"><a href="manipulação-de-dados.html#cb213-12" tabindex="-1"></a><span class="do">## # A tibble: 5 × 3</span></span>
<span id="cb213-13"><a href="manipulação-de-dados.html#cb213-13" tabindex="-1"></a><span class="do">##       x y         z</span></span>
<span id="cb213-14"><a href="manipulação-de-dados.html#cb213-14" tabindex="-1"></a><span class="do">##   &lt;int&gt; &lt;chr&gt; &lt;dbl&gt;</span></span>
<span id="cb213-15"><a href="manipulação-de-dados.html#cb213-15" tabindex="-1"></a><span class="do">## 1     1 A         2</span></span>
<span id="cb213-16"><a href="manipulação-de-dados.html#cb213-16" tabindex="-1"></a><span class="do">## 2     2 B         4</span></span>
<span id="cb213-17"><a href="manipulação-de-dados.html#cb213-17" tabindex="-1"></a><span class="do">## 3     3 C         6</span></span>
<span id="cb213-18"><a href="manipulação-de-dados.html#cb213-18" tabindex="-1"></a><span class="do">## 4     4 D         8</span></span>
<span id="cb213-19"><a href="manipulação-de-dados.html#cb213-19" tabindex="-1"></a><span class="do">## 5     5 E        10</span></span></code></pre></div>
<p>Também pode converter um data frame existente para um tibble usando a
função <code>as_tibble()</code>:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="manipulação-de-dados.html#cb214-1" tabindex="-1"></a><span class="co"># Criar um data frame</span></span>
<span id="cb214-2"><a href="manipulação-de-dados.html#cb214-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb214-3"><a href="manipulação-de-dados.html#cb214-3" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb214-4"><a href="manipulação-de-dados.html#cb214-4" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span>)</span>
<span id="cb214-5"><a href="manipulação-de-dados.html#cb214-5" tabindex="-1"></a>)</span>
<span id="cb214-6"><a href="manipulação-de-dados.html#cb214-6" tabindex="-1"></a></span>
<span id="cb214-7"><a href="manipulação-de-dados.html#cb214-7" tabindex="-1"></a><span class="co"># Converter para tibble</span></span>
<span id="cb214-8"><a href="manipulação-de-dados.html#cb214-8" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(df)</span>
<span id="cb214-9"><a href="manipulação-de-dados.html#cb214-9" tabindex="-1"></a></span>
<span id="cb214-10"><a href="manipulação-de-dados.html#cb214-10" tabindex="-1"></a><span class="fu">print</span>(tb)</span>
<span id="cb214-11"><a href="manipulação-de-dados.html#cb214-11" tabindex="-1"></a><span class="do">## # A tibble: 5 × 2</span></span>
<span id="cb214-12"><a href="manipulação-de-dados.html#cb214-12" tabindex="-1"></a><span class="do">##       x y    </span></span>
<span id="cb214-13"><a href="manipulação-de-dados.html#cb214-13" tabindex="-1"></a><span class="do">##   &lt;int&gt; &lt;chr&gt;</span></span>
<span id="cb214-14"><a href="manipulação-de-dados.html#cb214-14" tabindex="-1"></a><span class="do">## 1     1 A    </span></span>
<span id="cb214-15"><a href="manipulação-de-dados.html#cb214-15" tabindex="-1"></a><span class="do">## 2     2 B    </span></span>
<span id="cb214-16"><a href="manipulação-de-dados.html#cb214-16" tabindex="-1"></a><span class="do">## 3     3 C    </span></span>
<span id="cb214-17"><a href="manipulação-de-dados.html#cb214-17" tabindex="-1"></a><span class="do">## 4     4 D    </span></span>
<span id="cb214-18"><a href="manipulação-de-dados.html#cb214-18" tabindex="-1"></a><span class="do">## 5     5 E</span></span></code></pre></div>
</div>
</div>
<div id="manipulação-de-dados-com-dplyr" class="section level2 hasAnchor" number="16.2">
<h2><span class="header-section-number">16.2</span> Manipulação de Dados com <code>dplyr</code><a href="#manipula%C3%A7%C3%A3o-de-dados-com-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O <code>dplyr</code> é um pacote fundamental no <code>tidyverse</code> para manipulação de
dados em R. Ele proporciona uma sintaxe mais limpa e legível para
operações comuns em data frames e tibbles, como seleção, filtragem,
mutação (criação/modificação de colunas), ordenação e agrupamento de
dados.</p>
<p>As principais funções do <code>dplyr</code> são:</p>
<ul>
<li><code>select()</code>: Seleciona colunas de um data frame.</li>
<li><code>arrange()</code>: Ordena as linhas de um data frame com base nos valores de uma ou
mais colunas.</li>
<li><code>filter()</code>: Filtra linhas com base em condições lógicas.</li>
<li><code>mutate()</code>: Adiciona novas colunas ou modifica colunas existentes.</li>
<li><code>group_by()</code>: Agrupa os dados com base nos valores de uma ou mais
colunas.</li>
<li><code>summarise()</code>: Resuma os dados, tipicamente usado após <code>group_by()</code>
para calcular estatísticas agregadas.</li>
</ul>
<p>Vamos explorar cada uma dessas funções usando o dataset <code>starwars</code>
disponível no pacote dplyr.</p>
<p>Assim, utilizaremos o objeto <code>sw</code> para acessar os dados.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="manipulação-de-dados.html#cb215-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="manipulação-de-dados.html#cb219-1" tabindex="-1"></a><span class="co"># Carregar o dataset Star Wars</span></span>
<span id="cb219-2"><a href="manipulação-de-dados.html#cb219-2" tabindex="-1"></a>sw <span class="ot">&lt;-</span> starwars</span>
<span id="cb219-3"><a href="manipulação-de-dados.html#cb219-3" tabindex="-1"></a><span class="fu">glimpse</span>(sw) <span class="co"># Exibe uma visão geral dos dados</span></span></code></pre></div>
<pre><code>## Rows: 87
## Columns: 14
## $ name       &lt;chr&gt; &quot;Luke Skywalker&quot;, &quot;C-3PO&quot;, &quot;R2-D2&quot;, &quot;Darth Vader&quot;, &quot;Leia Or…
## $ height     &lt;int&gt; 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 2…
## $ mass       &lt;dbl&gt; 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.…
## $ hair_color &lt;chr&gt; &quot;blond&quot;, NA, NA, &quot;none&quot;, &quot;brown&quot;, &quot;brown, grey&quot;, &quot;brown&quot;, N…
## $ skin_color &lt;chr&gt; &quot;fair&quot;, &quot;gold&quot;, &quot;white, blue&quot;, &quot;white&quot;, &quot;light&quot;, &quot;light&quot;, &quot;…
## $ eye_color  &lt;chr&gt; &quot;blue&quot;, &quot;yellow&quot;, &quot;red&quot;, &quot;yellow&quot;, &quot;brown&quot;, &quot;blue&quot;, &quot;blue&quot;,…
## $ birth_year &lt;dbl&gt; 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, …
## $ sex        &lt;chr&gt; &quot;male&quot;, &quot;none&quot;, &quot;none&quot;, &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;,…
## $ gender     &lt;chr&gt; &quot;masculine&quot;, &quot;masculine&quot;, &quot;masculine&quot;, &quot;masculine&quot;, &quot;femini…
## $ homeworld  &lt;chr&gt; &quot;Tatooine&quot;, &quot;Tatooine&quot;, &quot;Naboo&quot;, &quot;Tatooine&quot;, &quot;Alderaan&quot;, &quot;T…
## $ species    &lt;chr&gt; &quot;Human&quot;, &quot;Droid&quot;, &quot;Droid&quot;, &quot;Human&quot;, &quot;Human&quot;, &quot;Human&quot;, &quot;Huma…
## $ films      &lt;list&gt; &lt;&quot;A New Hope&quot;, &quot;The Empire Strikes Back&quot;, &quot;Return of the J…
## $ vehicles   &lt;list&gt; &lt;&quot;Snowspeeder&quot;, &quot;Imperial Speeder Bike&quot;&gt;, &lt;&gt;, &lt;&gt;, &lt;&gt;, &quot;Imp…
## $ starships  &lt;list&gt; &lt;&quot;X-wing&quot;, &quot;Imperial shuttle&quot;&gt;, &lt;&gt;, &lt;&gt;, &quot;TIE Advanced x1&quot;,…</code></pre>
<div id="seleção-de-colunas-com-select" class="section level3 hasAnchor" number="16.2.1">
<h3><span class="header-section-number">16.2.1</span> Seleção de Colunas com <code>select()</code><a href="#sele%C3%A7%C3%A3o-de-colunas-com-select" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A função <code>select()</code> é usada para selecionar uma ou mais colunas de um
tibble ou data frame. Pode usar nomes de colunas diretamente sem aspas.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="manipulação-de-dados.html#cb221-1" tabindex="-1"></a><span class="co"># Selecionar uma coluna</span></span>
<span id="cb221-2"><a href="manipulação-de-dados.html#cb221-2" tabindex="-1"></a><span class="fu">select</span>(sw, name)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 1
##    name              
##    &lt;chr&gt;             
##  1 Luke Skywalker    
##  2 C-3PO             
##  3 R2-D2             
##  4 Darth Vader       
##  5 Leia Organa       
##  6 Owen Lars         
##  7 Beru Whitesun Lars
##  8 R5-D4             
##  9 Biggs Darklighter 
## 10 Obi-Wan Kenobi    
## # ℹ 77 more rows</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="manipulação-de-dados.html#cb223-1" tabindex="-1"></a><span class="co"># Selecionar várias colunas</span></span>
<span id="cb223-2"><a href="manipulação-de-dados.html#cb223-2" tabindex="-1"></a><span class="fu">select</span>(sw, name, mass, hair_color)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 3
##    name                mass hair_color   
##    &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;        
##  1 Luke Skywalker        77 blond        
##  2 C-3PO                 75 &lt;NA&gt;         
##  3 R2-D2                 32 &lt;NA&gt;         
##  4 Darth Vader          136 none         
##  5 Leia Organa           49 brown        
##  6 Owen Lars            120 brown, grey  
##  7 Beru Whitesun Lars    75 brown        
##  8 R5-D4                 32 &lt;NA&gt;         
##  9 Biggs Darklighter     84 black        
## 10 Obi-Wan Kenobi        77 auburn, white
## # ℹ 77 more rows</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="manipulação-de-dados.html#cb225-1" tabindex="-1"></a><span class="co"># Selecionar um intervalo de colunas</span></span>
<span id="cb225-2"><a href="manipulação-de-dados.html#cb225-2" tabindex="-1"></a><span class="fu">select</span>(sw, name<span class="sc">:</span>hair_color)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 4
##    name               height  mass hair_color   
##    &lt;chr&gt;               &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;        
##  1 Luke Skywalker        172    77 blond        
##  2 C-3PO                 167    75 &lt;NA&gt;         
##  3 R2-D2                  96    32 &lt;NA&gt;         
##  4 Darth Vader           202   136 none         
##  5 Leia Organa           150    49 brown        
##  6 Owen Lars             178   120 brown, grey  
##  7 Beru Whitesun Lars    165    75 brown        
##  8 R5-D4                  97    32 &lt;NA&gt;         
##  9 Biggs Darklighter     183    84 black        
## 10 Obi-Wan Kenobi        182    77 auburn, white
## # ℹ 77 more rows</code></pre>
<p>O <code>dplyr</code> possui um conjunto de funções auxiliares muito úteis para
seleção de colunas. As principais são:</p>
<ul>
<li><code>starts_with()</code>: para colunas que começam com um texto específico.</li>
<li><code>ends_with()</code>: para colunas que terminam com um texto específico.</li>
<li><code>contains()</code>: para colunas que contêm um texto específico.</li>
</ul>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="manipulação-de-dados.html#cb227-1" tabindex="-1"></a><span class="co"># Selecionar colunas que terminam com &quot;color&quot;</span></span>
<span id="cb227-2"><a href="manipulação-de-dados.html#cb227-2" tabindex="-1"></a><span class="fu">select</span>(sw, <span class="fu">ends_with</span>(<span class="st">&quot;color&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 3
##    hair_color    skin_color  eye_color
##    &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;    
##  1 blond         fair        blue     
##  2 &lt;NA&gt;          gold        yellow   
##  3 &lt;NA&gt;          white, blue red      
##  4 none          white       yellow   
##  5 brown         light       brown    
##  6 brown, grey   light       blue     
##  7 brown         light       blue     
##  8 &lt;NA&gt;          white, red  red      
##  9 black         light       brown    
## 10 auburn, white fair        blue-gray
## # ℹ 77 more rows</code></pre>
<p>Para remover colunas, basta acrescentar um <code>-</code> antes da seleção.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="manipulação-de-dados.html#cb229-1" tabindex="-1"></a><span class="fu">select</span>(sw, <span class="sc">-</span>name, <span class="sc">-</span>hair_color)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 12
##    height  mass skin_color  eye_color birth_year sex    gender homeworld species
##     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;  
##  1    172    77 fair        blue            19   male   mascu… Tatooine  Human  
##  2    167    75 gold        yellow         112   none   mascu… Tatooine  Droid  
##  3     96    32 white, blue red             33   none   mascu… Naboo     Droid  
##  4    202   136 white       yellow          41.9 male   mascu… Tatooine  Human  
##  5    150    49 light       brown           19   female femin… Alderaan  Human  
##  6    178   120 light       blue            52   male   mascu… Tatooine  Human  
##  7    165    75 light       blue            47   female femin… Tatooine  Human  
##  8     97    32 white, red  red             NA   none   mascu… Tatooine  Droid  
##  9    183    84 light       brown           24   male   mascu… Tatooine  Human  
## 10    182    77 fair        blue-gray       57   male   mascu… Stewjon   Human  
## # ℹ 77 more rows
## # ℹ 3 more variables: films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="manipulação-de-dados.html#cb231-1" tabindex="-1"></a><span class="co"># Remover múltiplas colunas</span></span>
<span id="cb231-2"><a href="manipulação-de-dados.html#cb231-2" tabindex="-1"></a><span class="fu">select</span>(sw, <span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">&quot;color&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 11
##    name    height  mass birth_year sex   gender homeworld species films vehicles
##    &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;   &lt;lis&gt; &lt;list&gt;  
##  1 Luke S…    172    77       19   male  mascu… Tatooine  Human   &lt;chr&gt; &lt;chr&gt;   
##  2 C-3PO      167    75      112   none  mascu… Tatooine  Droid   &lt;chr&gt; &lt;chr&gt;   
##  3 R2-D2       96    32       33   none  mascu… Naboo     Droid   &lt;chr&gt; &lt;chr&gt;   
##  4 Darth …    202   136       41.9 male  mascu… Tatooine  Human   &lt;chr&gt; &lt;chr&gt;   
##  5 Leia O…    150    49       19   fema… femin… Alderaan  Human   &lt;chr&gt; &lt;chr&gt;   
##  6 Owen L…    178   120       52   male  mascu… Tatooine  Human   &lt;chr&gt; &lt;chr&gt;   
##  7 Beru W…    165    75       47   fema… femin… Tatooine  Human   &lt;chr&gt; &lt;chr&gt;   
##  8 R5-D4       97    32       NA   none  mascu… Tatooine  Droid   &lt;chr&gt; &lt;chr&gt;   
##  9 Biggs …    183    84       24   male  mascu… Tatooine  Human   &lt;chr&gt; &lt;chr&gt;   
## 10 Obi-Wa…    182    77       57   male  mascu… Stewjon   Human   &lt;chr&gt; &lt;chr&gt;   
## # ℹ 77 more rows
## # ℹ 1 more variable: starships &lt;list&gt;</code></pre>
</div>
<div id="exercícios-15" class="section level3 hasAnchor" number="16.2.2">
<h3><span class="header-section-number">16.2.2</span> Exercícios<a href="#exerc%C3%ADcios-15" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Utilize a base <code>sw</code> nos exercícios a seguir.</p>
<p><strong>1.</strong> Utilize a função <code>glimpse()</code> do pacote <code>dplyr</code> na base <code>sw</code>. O
que ela faz?</p>
<p><strong>2.</strong> Crie uma tabela chamada <code>sw_simples</code> contendo apenas as colunas
<code>name</code>, <code>gender</code> e <code>films</code>.</p>
<p><strong>3.</strong> Selecione apenas as colunas <code>hair_color</code>, <code>skin_color</code> e
<code>eye_color</code> usando a função auxiliar <code>contains()</code>.</p>
<p><strong>4.</strong> Usando a função <code>select()</code> e as suas funções auxiliares, escreva
códigos que retornem a base <code>sw</code> sem as colunas <code>hair_color</code>,
<code>skin_color</code> e <code>eye_color</code>. Escreva todas as soluções diferentes que
conseguir pensar.</p>
</div>
<div id="ordenando-a-base-de-dados" class="section level3 hasAnchor" number="16.2.3">
<h3><span class="header-section-number">16.2.3</span> Ordenando a Base de Dados<a href="manipulação-de-dados.html#ordenando-a-base-de-dados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A função <code>arrange()</code> permite ordenar as linhas de uma tabela com base
nos valores de uma ou mais colunas. Pode ordenar em ordem crescente ou
decrescente, conforme a necessidade.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="manipulação-de-dados.html#cb233-1" tabindex="-1"></a><span class="co"># Exemplo de ordenação crescente</span></span>
<span id="cb233-2"><a href="manipulação-de-dados.html#cb233-2" tabindex="-1"></a><span class="fu">arrange</span>(sw, mass)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Ratts T…     79    15 none       grey, blue unknown           NA male  mascu…
##  2 Yoda         66    17 white      green      brown            896 male  mascu…
##  3 Wicket …     88    20 brown      brown      brown              8 male  mascu…
##  4 R2-D2        96    32 &lt;NA&gt;       white, bl… red               33 none  mascu…
##  5 R5-D4        97    32 &lt;NA&gt;       white, red red               NA none  mascu…
##  6 Sebulba     112    40 none       grey, red  orange            NA male  mascu…
##  7 Padmé A…    185    45 brown      light      brown             46 fema… femin…
##  8 Dud Bolt     94    45 none       blue, grey yellow            NA male  mascu…
##  9 Wat Tam…    193    48 none       green, gr… unknown           NA male  mascu…
## 10 Sly Moo…    178    48 none       pale       white             NA &lt;NA&gt;  &lt;NA&gt;  
## # ℹ 77 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="manipulação-de-dados.html#cb235-1" tabindex="-1"></a><span class="co"># Exemplo de ordenação decrescente</span></span>
<span id="cb235-2"><a href="manipulação-de-dados.html#cb235-2" tabindex="-1"></a><span class="fu">arrange</span>(sw, <span class="fu">desc</span>(mass))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Jabba D…    175  1358 &lt;NA&gt;       green-tan… orange         600   herm… mascu…
##  2 Grievous    216   159 none       brown, wh… green, y…       NA   male  mascu…
##  3 IG-88       200   140 none       metal      red             15   none  mascu…
##  4 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  5 Tarfful     234   136 brown      brown      blue            NA   male  mascu…
##  6 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  7 Bossk       190   113 none       green      red             53   male  mascu…
##  8 Chewbac…    228   112 brown      unknown    blue           200   male  mascu…
##  9 Jek Ton…    180   110 brown      fair       blue            NA   &lt;NA&gt;  &lt;NA&gt;  
## 10 Dexter …    198   102 none       brown      yellow          NA   male  mascu…
## # ℹ 77 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="manipulação-de-dados.html#cb237-1" tabindex="-1"></a><span class="co"># Ordenar por múltiplas colunas</span></span>
<span id="cb237-2"><a href="manipulação-de-dados.html#cb237-2" tabindex="-1"></a><span class="fu">arrange</span>(sw, <span class="fu">desc</span>(height), <span class="fu">desc</span>(mass))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Yarael …    264    NA none       white      yellow          NA   male  mascu…
##  2 Tarfful     234   136 brown      brown      blue            NA   male  mascu…
##  3 Lama Su     229    88 none       grey       black           NA   male  mascu…
##  4 Chewbac…    228   112 brown      unknown    blue           200   male  mascu…
##  5 Roos Ta…    224    82 none       grey       orange          NA   male  mascu…
##  6 Grievous    216   159 none       brown, wh… green, y…       NA   male  mascu…
##  7 Taun We     213    NA none       grey       black           NA   fema… femin…
##  8 Tion Me…    206    80 none       grey       black           NA   male  mascu…
##  9 Rugor N…    206    NA none       green      orange          NA   male  mascu…
## 10 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
## # ℹ 77 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="exercícios-16" class="section level3 hasAnchor" number="16.2.4">
<h3><span class="header-section-number">16.2.4</span> Exercícios<a href="#exerc%C3%ADcios-16" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1.</strong> Ordene a base <code>sw</code> pela coluna <code>mass</code> em ordem crescente e pela
coluna <code>birth_year</code> em ordem decrescente. Guarde o resultado em um
objeto chamado <code>sw_ordenados</code>.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="manipulação-de-dados.html#cb239-1" tabindex="-1"></a>sw_ordenados <span class="ot">&lt;-</span> <span class="fu">arrange</span>(sw, mass, <span class="fu">desc</span>(birth_year))</span>
<span id="cb239-2"><a href="manipulação-de-dados.html#cb239-2" tabindex="-1"></a>sw_ordenados</span></code></pre></div>
<p><strong>2.</strong> Selecione apenas as colunas <code>name</code> e <code>birth_year</code>, então ordene
de forma decrescente pelo <code>birth_year</code>.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="manipulação-de-dados.html#cb240-1" tabindex="-1"></a><span class="co"># Usando aninhamento de funções</span></span>
<span id="cb240-2"><a href="manipulação-de-dados.html#cb240-2" tabindex="-1"></a><span class="fu">arrange</span>(<span class="fu">select</span>(sw, name, birth_year), <span class="fu">desc</span>(birth_year))</span>
<span id="cb240-3"><a href="manipulação-de-dados.html#cb240-3" tabindex="-1"></a></span>
<span id="cb240-4"><a href="manipulação-de-dados.html#cb240-4" tabindex="-1"></a><span class="co"># Usando um objeto intermediário</span></span>
<span id="cb240-5"><a href="manipulação-de-dados.html#cb240-5" tabindex="-1"></a>sw_aux <span class="ot">&lt;-</span> <span class="fu">select</span>(sw, name, birth_year)</span>
<span id="cb240-6"><a href="manipulação-de-dados.html#cb240-6" tabindex="-1"></a><span class="fu">arrange</span>(sw_aux, <span class="fu">desc</span>(birth_year))</span>
<span id="cb240-7"><a href="manipulação-de-dados.html#cb240-7" tabindex="-1"></a></span>
<span id="cb240-8"><a href="manipulação-de-dados.html#cb240-8" tabindex="-1"></a><span class="co"># Usando pipes para simplificar</span></span>
<span id="cb240-9"><a href="manipulação-de-dados.html#cb240-9" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> </span>
<span id="cb240-10"><a href="manipulação-de-dados.html#cb240-10" tabindex="-1"></a>  <span class="fu">select</span>(name, birth_year) <span class="sc">%&gt;%</span> </span>
<span id="cb240-11"><a href="manipulação-de-dados.html#cb240-11" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(birth_year))</span></code></pre></div>
</div>
<div id="filtrando-linhas-da-base-de-dados" class="section level3 hasAnchor" number="16.2.5">
<h3><span class="header-section-number">16.2.5</span> Filtrando Linhas da Base de Dados<a href="manipulação-de-dados.html#filtrando-linhas-da-base-de-dados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para selecionar linhas específicas com base em uma ou mais condições,
utilizamos a função <code>filter()</code>.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="manipulação-de-dados.html#cb241-1" tabindex="-1"></a><span class="co"># filter(sw, height &gt; 170)</span></span>
<span id="cb241-2"><a href="manipulação-de-dados.html#cb241-2" tabindex="-1"></a><span class="co"># Ou</span></span>
<span id="cb241-3"><a href="manipulação-de-dados.html#cb241-3" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">filter</span>(height <span class="sc">&gt;</span> <span class="dv">170</span>)</span></code></pre></div>
<pre><code>## # A tibble: 55 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke Sk…    172    77 blond      fair       blue            19   male  mascu…
##  2 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  3 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  4 Biggs D…    183    84 black      light      brown           24   male  mascu…
##  5 Obi-Wan…    182    77 auburn, w… fair       blue-gray       57   male  mascu…
##  6 Anakin …    188    84 blond      fair       blue            41.9 male  mascu…
##  7 Wilhuff…    180    NA auburn, g… fair       blue            64   male  mascu…
##  8 Chewbac…    228   112 brown      unknown    blue           200   male  mascu…
##  9 Han Solo    180    80 brown      fair       brown           29   male  mascu…
## 10 Greedo      173    74 &lt;NA&gt;       green      black           44   male  mascu…
## # ℹ 45 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Podemos selecionar apenas as colunas <code>name</code> e <code>height</code> para
visualizarmos as alturas:</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="manipulação-de-dados.html#cb243-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> </span>
<span id="cb243-2"><a href="manipulação-de-dados.html#cb243-2" tabindex="-1"></a>  <span class="fu">filter</span>(height <span class="sc">&gt;</span> <span class="dv">170</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb243-3"><a href="manipulação-de-dados.html#cb243-3" tabindex="-1"></a>  <span class="fu">select</span>(name, height)</span></code></pre></div>
<pre><code>## # A tibble: 55 × 2
##    name              height
##    &lt;chr&gt;              &lt;int&gt;
##  1 Luke Skywalker       172
##  2 Darth Vader          202
##  3 Owen Lars            178
##  4 Biggs Darklighter    183
##  5 Obi-Wan Kenobi       182
##  6 Anakin Skywalker     188
##  7 Wilhuff Tarkin       180
##  8 Chewbacca            228
##  9 Han Solo             180
## 10 Greedo               173
## # ℹ 45 more rows</code></pre>
<p>Podemos estender o filtro para duas ou mais colunas.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="manipulação-de-dados.html#cb245-1" tabindex="-1"></a><span class="fu">filter</span>(sw, height<span class="sc">&gt;</span><span class="dv">170</span>, mass<span class="sc">&gt;</span><span class="dv">80</span>)</span></code></pre></div>
<pre><code>## # A tibble: 21 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  2 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  3 Biggs D…    183    84 black      light      brown           24   male  mascu…
##  4 Anakin …    188    84 blond      fair       blue            41.9 male  mascu…
##  5 Chewbac…    228   112 brown      unknown    blue           200   male  mascu…
##  6 Jabba D…    175  1358 &lt;NA&gt;       green-tan… orange         600   herm… mascu…
##  7 Jek Ton…    180   110 brown      fair       blue            NA   &lt;NA&gt;  &lt;NA&gt;  
##  8 IG-88       200   140 none       metal      red             15   none  mascu…
##  9 Bossk       190   113 none       green      red             53   male  mascu…
## 10 Ackbar      180    83 none       brown mot… orange          41   male  mascu…
## # ℹ 11 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="manipulação-de-dados.html#cb247-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">filter</span>(height <span class="sc">&gt;</span> <span class="dv">170</span>, mass <span class="sc">&gt;</span> <span class="dv">80</span>)</span></code></pre></div>
<pre><code>## # A tibble: 21 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  2 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  3 Biggs D…    183    84 black      light      brown           24   male  mascu…
##  4 Anakin …    188    84 blond      fair       blue            41.9 male  mascu…
##  5 Chewbac…    228   112 brown      unknown    blue           200   male  mascu…
##  6 Jabba D…    175  1358 &lt;NA&gt;       green-tan… orange         600   herm… mascu…
##  7 Jek Ton…    180   110 brown      fair       blue            NA   &lt;NA&gt;  &lt;NA&gt;  
##  8 IG-88       200   140 none       metal      red             15   none  mascu…
##  9 Bossk       190   113 none       green      red             53   male  mascu…
## 10 Ackbar      180    83 none       brown mot… orange          41   male  mascu…
## # ℹ 11 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Podemos filtrar colunas categóricas. O exemplo abaixo retorna uma tabela
apenas com os personagens com cabelo preto ou castanho.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="manipulação-de-dados.html#cb249-1" tabindex="-1"></a><span class="co"># Filtrar texto com correspondência exata</span></span>
<span id="cb249-2"><a href="manipulação-de-dados.html#cb249-2" tabindex="-1"></a><span class="fu">filter</span>(sw, hair_color <span class="sc">==</span> <span class="st">&quot;black&quot;</span> <span class="sc">|</span> hair_color <span class="sc">==</span> <span class="st">&quot;brown&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 31 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Leia Or…    150  49   brown      light      brown           19   fema… femin…
##  2 Beru Wh…    165  75   brown      light      blue            47   fema… femin…
##  3 Biggs D…    183  84   black      light      brown           24   male  mascu…
##  4 Chewbac…    228 112   brown      unknown    blue           200   male  mascu…
##  5 Han Solo    180  80   brown      fair       brown           29   male  mascu…
##  6 Wedge A…    170  77   brown      fair       hazel           21   male  mascu…
##  7 Jek Ton…    180 110   brown      fair       blue            NA   &lt;NA&gt;  &lt;NA&gt;  
##  8 Boba Fe…    183  78.2 black      fair       brown           31.5 male  mascu…
##  9 Lando C…    177  79   black      dark       brown           31   male  mascu…
## 10 Arvel C…     NA  NA   brown      fair       brown           NA   male  mascu…
## # ℹ 21 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="manipulação-de-dados.html#cb251-1" tabindex="-1"></a><span class="co"># Filtrar texto com correspondência exata</span></span>
<span id="cb251-2"><a href="manipulação-de-dados.html#cb251-2" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">filter</span>(hair_color <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;brown&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 31 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Leia Or…    150  49   brown      light      brown           19   fema… femin…
##  2 Beru Wh…    165  75   brown      light      blue            47   fema… femin…
##  3 Biggs D…    183  84   black      light      brown           24   male  mascu…
##  4 Chewbac…    228 112   brown      unknown    blue           200   male  mascu…
##  5 Han Solo    180  80   brown      fair       brown           29   male  mascu…
##  6 Wedge A…    170  77   brown      fair       hazel           21   male  mascu…
##  7 Jek Ton…    180 110   brown      fair       blue            NA   &lt;NA&gt;  &lt;NA&gt;  
##  8 Boba Fe…    183  78.2 black      fair       brown           31.5 male  mascu…
##  9 Lando C…    177  79   black      dark       brown           31   male  mascu…
## 10 Arvel C…     NA  NA   brown      fair       brown           NA   male  mascu…
## # ℹ 21 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Para filtrar textos sem correspondência exata, podemos utilizar a função
auxiliar <code>str_detect()</code> do pacote <code>{stringr}</code>. Ela serve para verificar
se cada string de um vetor contém um determinado padrão de texto.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="manipulação-de-dados.html#cb253-1" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb253-2"><a href="manipulação-de-dados.html#cb253-2" tabindex="-1"></a></span>
<span id="cb253-3"><a href="manipulação-de-dados.html#cb253-3" tabindex="-1"></a><span class="fu">str_detect</span>(</span>
<span id="cb253-4"><a href="manipulação-de-dados.html#cb253-4" tabindex="-1"></a>  <span class="at">string =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;aa&quot;</span>,<span class="st">&quot;abc&quot;</span>, <span class="st">&quot;bc&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="cn">NA</span>), </span>
<span id="cb253-5"><a href="manipulação-de-dados.html#cb253-5" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="st">&quot;a&quot;</span></span>
<span id="cb253-6"><a href="manipulação-de-dados.html#cb253-6" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE FALSE    NA</code></pre>
<p>Podemos utilizá-la para filtrar apenas os personagens com cabelo <code>grey</code>.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="manipulação-de-dados.html#cb255-1" tabindex="-1"></a><span class="co"># Podemos detetar se o cabelo grey aparece na string</span></span>
<span id="cb255-2"><a href="manipulação-de-dados.html#cb255-2" tabindex="-1"></a><span class="fu">str_detect</span>(</span>
<span id="cb255-3"><a href="manipulação-de-dados.html#cb255-3" tabindex="-1"></a>  <span class="at">string =</span> sw<span class="sc">$</span>hair_color,</span>
<span id="cb255-4"><a href="manipulação-de-dados.html#cb255-4" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="st">&quot;grey&quot;</span></span>
<span id="cb255-5"><a href="manipulação-de-dados.html#cb255-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  [1] FALSE    NA    NA FALSE FALSE  TRUE FALSE    NA FALSE FALSE FALSE  TRUE
## [13] FALSE FALSE    NA    NA FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
## [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [85] FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="manipulação-de-dados.html#cb257-1" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb257-2"><a href="manipulação-de-dados.html#cb257-2" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(hair_color,<span class="st">&quot;grey&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Owen Lars    178   120 brown, gr… light      blue              52 male  mascu…
## 2 Wilhuff …    180    NA auburn, g… fair       blue              64 male  mascu…
## 3 Palpatine    170    75 grey       pale       yellow            82 male  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="exercícios-17" class="section level3 hasAnchor" number="16.2.6">
<h3><span class="header-section-number">16.2.6</span> Exercícios<a href="#exerc%C3%ADcios-17" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Utilize a base <code>sw</code> nos exercícios a seguir.</p>
<p><strong>1.</strong> Crie um objeto chamado <code>humanos</code> apenas com personagens que sejam
humanos.</p>
<p><strong>2.</strong> Crie um objeto chamado <code>altos_fortes</code> com personagens que tenham
mais de 200 cm de altura e peso maior que 100 kg.</p>
<p><strong>3.</strong> Retorne tabelas (<code>tibbles</code>) apenas com:</p>
<p><strong>a.</strong> Personagens humanos que nasceram antes de 100 anos antes da
batalha de Yavin (<code>birth_year &lt; 100</code>).</p>
<p><strong>b.</strong> Personagens com cor <code>light</code> ou <code>red</code>.</p>
<p><strong>c.</strong> Personagens com massa maior que 100 kg, ordenados de forma
decrescente por altura, mostrando apenas as colunas <code>name</code>, <code>mass</code> e
<code>height</code>.</p>
<p><strong>d.</strong> Personagens que sejam “Humano” ou “Droid”, e tenham uma altura
maior que 170 cm.</p>
<p><strong>e.</strong> Personagens que não possuem informação tanto de altura (<code>height</code>)
quanto de massa (<code>mass</code>), ou seja, possuem <code>NA</code> em ambas as colunas.</p>
</div>
<div id="modificar-e-criar-novas-colunas" class="section level3 hasAnchor" number="16.2.7">
<h3><span class="header-section-number">16.2.7</span> Modificar e criar novas colunas<a href="manipulação-de-dados.html#modificar-e-criar-novas-colunas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A função <code>mutate()</code> permite criar novas colunas ou modificar colunas
existentes, facilitando transformações de dados. O código abaixo divide
os valores da coluna <code>height</code> por 100, mudando a unidade de medida dessa
variável de centímetros para metros.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="manipulação-de-dados.html#cb259-1" tabindex="-1"></a><span class="co"># Modificar a unidade de medida da coluna height</span></span>
<span id="cb259-2"><a href="manipulação-de-dados.html#cb259-2" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">height =</span> height<span class="sc">/</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke Sk…   1.72    77 blond      fair       blue            19   male  mascu…
##  2 C-3PO      1.67    75 &lt;NA&gt;       gold       yellow         112   none  mascu…
##  3 R2-D2      0.96    32 &lt;NA&gt;       white, bl… red             33   none  mascu…
##  4 Darth V…   2.02   136 none       white      yellow          41.9 male  mascu…
##  5 Leia Or…   1.5     49 brown      light      brown           19   fema… femin…
##  6 Owen La…   1.78   120 brown, gr… light      blue            52   male  mascu…
##  7 Beru Wh…   1.65    75 brown      light      blue            47   fema… femin…
##  8 R5-D4      0.97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
##  9 Biggs D…   1.83    84 black      light      brown           24   male  mascu…
## 10 Obi-Wan…   1.82    77 auburn, w… fair       blue-gray       57   male  mascu…
## # ℹ 77 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Também poderíamos ter criado essa variável em uma nova coluna. Repare
que a nova coluna <code>height_meters</code> é colocada no final da tabela.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="manipulação-de-dados.html#cb261-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">height_meters =</span> height<span class="sc">/</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 15
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke Sk…    172    77 blond      fair       blue            19   male  mascu…
##  2 C-3PO       167    75 &lt;NA&gt;       gold       yellow         112   none  mascu…
##  3 R2-D2        96    32 &lt;NA&gt;       white, bl… red             33   none  mascu…
##  4 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  5 Leia Or…    150    49 brown      light      brown           19   fema… femin…
##  6 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  7 Beru Wh…    165    75 brown      light      blue            47   fema… femin…
##  8 R5-D4        97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
##  9 Biggs D…    183    84 black      light      brown           24   male  mascu…
## 10 Obi-Wan…    182    77 auburn, w… fair       blue-gray       57   male  mascu…
## # ℹ 77 more rows
## # ℹ 6 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;, height_meters &lt;dbl&gt;</code></pre>
<p>Podemos fazer qualquer operação com uma ou mais colunas. Abaixo vamos
criar um tibble que contenha as colunas <code>name</code>, <code>height</code>, <code>mass</code>, e uma
nova coluna <code>BMI</code>, que calcule o Índice de Massa Corporal (IMC) de cada
personagem, usando a fórmula <code>mass / (height/100)^2</code>. Caso <code>height</code> ou
<code>mass</code> seja <code>NA</code>, a coluna <code>BMI</code> deve ser <code>NA</code>.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="manipulação-de-dados.html#cb263-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span></span>
<span id="cb263-2"><a href="manipulação-de-dados.html#cb263-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">BMI =</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(height) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(mass), mass <span class="sc">/</span> (height<span class="sc">/</span><span class="dv">100</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="cn">NA</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb263-3"><a href="manipulação-de-dados.html#cb263-3" tabindex="-1"></a>  <span class="fu">select</span>(name, height, mass, BMI)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 4
##    name               height  mass   BMI
##    &lt;chr&gt;               &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 Luke Skywalker        172    77  26.0
##  2 C-3PO                 167    75  26.9
##  3 R2-D2                  96    32  34.7
##  4 Darth Vader           202   136  33.3
##  5 Leia Organa           150    49  21.8
##  6 Owen Lars             178   120  37.9
##  7 Beru Whitesun Lars    165    75  27.5
##  8 R5-D4                  97    32  34.0
##  9 Biggs Darklighter     183    84  25.1
## 10 Obi-Wan Kenobi        182    77  23.2
## # ℹ 77 more rows</code></pre>
</div>
<div id="exercícios-18" class="section level3 hasAnchor" number="16.2.8">
<h3><span class="header-section-number">16.2.8</span> Exercícios<a href="#exerc%C3%ADcios-18" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1.</strong> Crie uma coluna chamada <code>dif_peso_altura</code> (diferença entre altura
e peso) e salve a nova tabela em um objeto chamado <code>starwars_dif</code>. Em
seguida, filtre apenas os personagens que têm altura maior que o peso e
ordene a tabela por ordem crescente de <code>dif_peso_altura</code>.</p>
<p><strong>2.</strong> Crie as seguintes colunas:</p>
<p><strong>a.</strong> <code>indice_massa_altura</code> = <code>mass</code> / <code>height</code></p>
<p><strong>b.</strong> <code>indice_massa_medio</code> = <code>mean(mass, na.rm = TRUE)</code></p>
<p><strong>c.</strong> <code>indice_relativo</code> =
<code>(indice_massa_altura - indice_massa_medio) / indice_massa_medio</code></p>
<p><strong>d.</strong> <code>acima_media</code> =
<code>ifelse(indice_massa_altura &gt; indice_massa_medio, “sim”, “não”)</code></p>
<p><strong>3.</strong> Crie uma nova coluna que classifique o personagem em “recente”
(nascido após 100 anos antes da batalha de Yavin) e “antigo” (nascido há
100 anos ou mais).</p>
</div>
<div id="sumarizar-a-base-de-dados" class="section level3 hasAnchor" number="16.2.9">
<h3><span class="header-section-number">16.2.9</span> Sumarizar a Base de Dados<a href="manipulação-de-dados.html#sumarizar-a-base-de-dados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A função <code>summarize()</code> permite calcular estatísticas agregadas, como
média, mediana, variância, etc. Para agregar dados por categorias,
combinamos <code>summarize()</code> com <code>group_by()</code>.</p>
<p>O código abaixo resume a coluna <code>mass</code> pela sua média.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="manipulação-de-dados.html#cb265-1" tabindex="-1"></a><span class="co"># Exemplo de sumarização</span></span>
<span id="cb265-2"><a href="manipulação-de-dados.html#cb265-2" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">media_massa =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   media_massa
##         &lt;dbl&gt;
## 1        97.3</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="manipulação-de-dados.html#cb267-1" tabindex="-1"></a><span class="co"># Sumarização agrupada por categorias</span></span>
<span id="cb267-2"><a href="manipulação-de-dados.html#cb267-2" tabindex="-1"></a>sw <span class="sc">%&gt;%</span></span>
<span id="cb267-3"><a href="manipulação-de-dados.html#cb267-3" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb267-4"><a href="manipulação-de-dados.html#cb267-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">media_massa =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 38 × 2
##    species   media_massa
##    &lt;chr&gt;           &lt;dbl&gt;
##  1 Aleena           15  
##  2 Besalisk        102  
##  3 Cerean           82  
##  4 Chagrian        NaN  
##  5 Clawdite         55  
##  6 Droid            69.8
##  7 Dug              40  
##  8 Ewok             20  
##  9 Geonosian        80  
## 10 Gungan           74  
## # ℹ 28 more rows</code></pre>
<p>Podemos calcular ao mesmo tempo sumarizações diferentes.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="manipulação-de-dados.html#cb269-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(</span>
<span id="cb269-2"><a href="manipulação-de-dados.html#cb269-2" tabindex="-1"></a>  <span class="at">media_massa =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb269-3"><a href="manipulação-de-dados.html#cb269-3" tabindex="-1"></a>  <span class="at">mediana_massa =</span> <span class="fu">median</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb269-4"><a href="manipulação-de-dados.html#cb269-4" tabindex="-1"></a>  <span class="at">variancia_massa =</span> <span class="fu">var</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb269-5"><a href="manipulação-de-dados.html#cb269-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   media_massa mediana_massa variancia_massa
##         &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;
## 1        97.3            79          28716.</code></pre>
<p>Podemos também sumarizar diversas colunas.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="manipulação-de-dados.html#cb271-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(</span>
<span id="cb271-2"><a href="manipulação-de-dados.html#cb271-2" tabindex="-1"></a>  <span class="at">media_massa =</span> <span class="fu">mean</span>(mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb271-3"><a href="manipulação-de-dados.html#cb271-3" tabindex="-1"></a>  <span class="at">media_altura =</span> <span class="fu">mean</span>(height, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb271-4"><a href="manipulação-de-dados.html#cb271-4" tabindex="-1"></a>  <span class="at">media_ano =</span> <span class="fu">mean</span>(birth_year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb271-5"><a href="manipulação-de-dados.html#cb271-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   media_massa media_altura media_ano
##         &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;
## 1        97.3         175.      87.6</code></pre>
<p>Para sumarizar uma coluna agrupada pelas categorias de uma segunda
coluna usamos além do <code>summarize()</code> a função <code>group_by()</code>.</p>
<p>O código a abaixo calcula a altura média dos personagens para cada
categoria da coluna <code>hair_color</code>.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="manipulação-de-dados.html#cb273-1" tabindex="-1"></a>sw <span class="sc">%&gt;%</span> </span>
<span id="cb273-2"><a href="manipulação-de-dados.html#cb273-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(hair_color), <span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span> </span>
<span id="cb273-3"><a href="manipulação-de-dados.html#cb273-3" tabindex="-1"></a>  <span class="fu">group_by</span>(hair_color) <span class="sc">%&gt;%</span> </span>
<span id="cb273-4"><a href="manipulação-de-dados.html#cb273-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">media_altura =</span> <span class="fu">mean</span>(height, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 11 × 2
##    hair_color    media_altura
##    &lt;chr&gt;                &lt;dbl&gt;
##  1 auburn                150 
##  2 auburn, grey          180 
##  3 auburn, white         182 
##  4 black                 174.
##  5 blond                 177.
##  6 blonde                168 
##  7 brown                 177.
##  8 brown, grey           178 
##  9 grey                  170 
## 10 none                  181.
## 11 white                 156</code></pre>
</div>
<div id="exerícios" class="section level3 hasAnchor" number="16.2.10">
<h3><span class="header-section-number">16.2.10</span> Exerícios<a href="#exer%C3%ADcios" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Utilize a base <code>sw</code> nos exercícios a seguir.</p>
<p><strong>1.</strong> Calcule a altura média e mediana dos personagens.</p>
<p><strong>2.</strong> Calcule a massa média dos personagens cuja altura é maior que 175
cm.</p>
<p><strong>3.</strong> Apresente na mesma tabela a massa média dos personagens com
altura menor que 175 cm e a massa média dos personagens com altura maior
ou igual a 175 cm.</p>
<p><strong>4.</strong> Retorne tabelas (<code>tibbles</code>) apenas com:</p>
<p><strong>a.</strong> A altura média dos personagens por espécie. <strong>b.</strong> A massa média
e mediana dos personagens por espécie. <strong>c.</strong> Apenas o nome dos
personagens que participaram de mais de 2 filmes.</p>
</div>
<div id="juntando-tabelas-em-r-com-dplyr" class="section level3 hasAnchor" number="16.2.11">
<h3><span class="header-section-number">16.2.11</span> Juntando Tabelas em R com dplyr<a href="manipulação-de-dados.html#juntando-tabelas-em-r-com-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Em ciência de dados, é comum precisar combinar informações de diferentes
fontes em uma única tabela. No R, o pacote <code>dplyr</code> oferece várias
funções para realizar operações de junção, que permitem combinar duas ou
mais tabelas (data frames ou tibbles) com base em uma ou mais colunas
compartilhadas.</p>
<p><strong>Tipos de Junção</strong></p>
<p>As junções mais comuns em manipulação de dados são:</p>
<ul>
<li><code>left_join()</code>: Mantém todas as linhas da tabela à esquerda e
adiciona as colunas da tabela à direita onde há correspondência de
valores na coluna chave.</li>
<li><code>right_join()</code>: Mantém todas as linhas da tabela à direita e
adiciona as colunas da tabela à esquerda onde há correspondência.</li>
<li><code>full_join()</code>: Mantém todas as linhas de ambas as tabelas e adiciona
NA onde não há correspondência.</li>
</ul>
<p>Essas funções são extremamente úteis quando é necessário combinar dados
de diferentes fontes que compartilham uma chave comum, como um
identificador único.</p>
<p><strong>Exemplo</strong>: Personagens de Star Wars</p>
<p>Para ilustrar como estas funções funcionam, vamos usar a base de dados
<code>sw</code> e criar dois subconjuntos de dados:</p>
<ol style="list-style-type: decimal">
<li><code>personagens_altos</code>: Tabela contendo apenas personagens com altura
superior a 180 cm.</li>
<li><code>personagens_humanos</code>: Tabela contendo apenas personagens que são
humanos.</li>
</ol>
<p>Vamos criar os nossos subconjuntos de dados usando a função <code>filter()</code>
do dplyr.</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="manipulação-de-dados.html#cb275-1" tabindex="-1"></a><span class="co"># Criar subconjunto de personagens altos (altura &gt; 180 cm)</span></span>
<span id="cb275-2"><a href="manipulação-de-dados.html#cb275-2" tabindex="-1"></a>personagens_altos <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span></span>
<span id="cb275-3"><a href="manipulação-de-dados.html#cb275-3" tabindex="-1"></a>  <span class="fu">filter</span>(height <span class="sc">&gt;</span> <span class="dv">180</span>) <span class="sc">%&gt;%</span></span>
<span id="cb275-4"><a href="manipulação-de-dados.html#cb275-4" tabindex="-1"></a>  <span class="fu">select</span>(name, height)</span>
<span id="cb275-5"><a href="manipulação-de-dados.html#cb275-5" tabindex="-1"></a></span>
<span id="cb275-6"><a href="manipulação-de-dados.html#cb275-6" tabindex="-1"></a><span class="co"># Criar subconjunto de personagens humanos</span></span>
<span id="cb275-7"><a href="manipulação-de-dados.html#cb275-7" tabindex="-1"></a>personagens_humanos <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span></span>
<span id="cb275-8"><a href="manipulação-de-dados.html#cb275-8" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb275-9"><a href="manipulação-de-dados.html#cb275-9" tabindex="-1"></a>  <span class="fu">select</span>(name, species)</span></code></pre></div>
<p>Agora que temos duas tabelas, <code>personagens_altos</code> e
<code>personagens_humanos</code>, podemos usar as funções de junção para
combiná-las: <code>left_join()</code>, <code>right_join()</code>, e <code>full_join()</code>.</p>
<p>A função <code>left_join()</code> junta duas tabelas, mantendo todas as linhas da
tabela à esquerda (primeira tabela) e adicionando colunas da tabela à
direita (segunda tabela) para as quais existe uma correspondência.
Valores sem correspondência entre as bases receberão <code>NA</code> na nova base.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="manipulação-de-dados.html#cb276-1" tabindex="-1"></a><span class="co"># Combinar tabelas mantendo todas as linhas de personagens_altos</span></span>
<span id="cb276-2"><a href="manipulação-de-dados.html#cb276-2" tabindex="-1"></a>humanos_altos_left_join <span class="ot">&lt;-</span> <span class="fu">left_join</span>(personagens_altos, personagens_humanos, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span>
<span id="cb276-3"><a href="manipulação-de-dados.html#cb276-3" tabindex="-1"></a></span>
<span id="cb276-4"><a href="manipulação-de-dados.html#cb276-4" tabindex="-1"></a><span class="co"># Visualizar o resultado</span></span>
<span id="cb276-5"><a href="manipulação-de-dados.html#cb276-5" tabindex="-1"></a><span class="fu">print</span>(humanos_altos_left_join)</span></code></pre></div>
<pre><code>## # A tibble: 39 × 3
##    name              height species
##    &lt;chr&gt;              &lt;int&gt; &lt;chr&gt;  
##  1 Darth Vader          202 Human  
##  2 Biggs Darklighter    183 Human  
##  3 Obi-Wan Kenobi       182 Human  
##  4 Anakin Skywalker     188 Human  
##  5 Chewbacca            228 &lt;NA&gt;   
##  6 Boba Fett            183 Human  
##  7 IG-88                200 &lt;NA&gt;   
##  8 Bossk                190 &lt;NA&gt;   
##  9 Qui-Gon Jinn         193 Human  
## 10 Nute Gunray          191 &lt;NA&gt;   
## # ℹ 29 more rows</code></pre>
<p>Neste exemplo, a tabela resultante <code>humanos_altos_left_join</code> inclui
todos os personagens altos e adiciona informações sobre a espécie (se
disponível) da tabela <code>personagens_humanos</code>. Se um personagem não for
humano, as colunas de espécie serão preenchidas com <code>NA</code>.</p>
<p>A função <code>right_join()</code> faz o oposto de <code>left_join()</code>: mantém todas as
linhas da tabela à direita e adiciona colunas da tabela à esquerda para
as quais existe uma correspondência.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="manipulação-de-dados.html#cb278-1" tabindex="-1"></a><span class="co"># Combinar tabelas mantendo todas as linhas de personagens_humanos</span></span>
<span id="cb278-2"><a href="manipulação-de-dados.html#cb278-2" tabindex="-1"></a>humanos_altos_right_join <span class="ot">&lt;-</span> <span class="fu">right_join</span>(personagens_altos, personagens_humanos, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span>
<span id="cb278-3"><a href="manipulação-de-dados.html#cb278-3" tabindex="-1"></a></span>
<span id="cb278-4"><a href="manipulação-de-dados.html#cb278-4" tabindex="-1"></a><span class="co"># Visualizar o resultado</span></span>
<span id="cb278-5"><a href="manipulação-de-dados.html#cb278-5" tabindex="-1"></a><span class="fu">print</span>(humanos_altos_right_join)</span></code></pre></div>
<pre><code>## # A tibble: 35 × 3
##    name              height species
##    &lt;chr&gt;              &lt;int&gt; &lt;chr&gt;  
##  1 Darth Vader          202 Human  
##  2 Biggs Darklighter    183 Human  
##  3 Obi-Wan Kenobi       182 Human  
##  4 Anakin Skywalker     188 Human  
##  5 Boba Fett            183 Human  
##  6 Qui-Gon Jinn         193 Human  
##  7 Padmé Amidala        185 Human  
##  8 Ric Olié             183 Human  
##  9 Quarsh Panaka        183 Human  
## 10 Mace Windu           188 Human  
## # ℹ 25 more rows</code></pre>
<p>A tabela <code>humanos_altos_right_join</code> inclui todos os personagens humanos
e adiciona informações sobre a altura (se disponível) da tabela
<code>personagens_altos</code>. Se um personagem humano não for alto, a coluna de
altura será preenchida com <code>NA</code>.</p>
<p>A função <code>full_join()</code> mantém todas as linhas de ambas as tabelas e
adiciona <code>NA</code> onde não há correspondência.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="manipulação-de-dados.html#cb280-1" tabindex="-1"></a><span class="co"># Combinar todas as informações de personagens altos e humanos</span></span>
<span id="cb280-2"><a href="manipulação-de-dados.html#cb280-2" tabindex="-1"></a>humanos_altos_full_join <span class="ot">&lt;-</span> <span class="fu">full_join</span>(personagens_altos, personagens_humanos, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span>
<span id="cb280-3"><a href="manipulação-de-dados.html#cb280-3" tabindex="-1"></a></span>
<span id="cb280-4"><a href="manipulação-de-dados.html#cb280-4" tabindex="-1"></a><span class="co"># Visualizar o resultado</span></span>
<span id="cb280-5"><a href="manipulação-de-dados.html#cb280-5" tabindex="-1"></a><span class="fu">print</span>(humanos_altos_full_join)</span></code></pre></div>
<pre><code>## # A tibble: 59 × 3
##    name              height species
##    &lt;chr&gt;              &lt;int&gt; &lt;chr&gt;  
##  1 Darth Vader          202 Human  
##  2 Biggs Darklighter    183 Human  
##  3 Obi-Wan Kenobi       182 Human  
##  4 Anakin Skywalker     188 Human  
##  5 Chewbacca            228 &lt;NA&gt;   
##  6 Boba Fett            183 Human  
##  7 IG-88                200 &lt;NA&gt;   
##  8 Bossk                190 &lt;NA&gt;   
##  9 Qui-Gon Jinn         193 Human  
## 10 Nute Gunray          191 &lt;NA&gt;   
## # ℹ 49 more rows</code></pre>
<p>A tabela <code>humanos_altos_full_join</code> contém todos os personagens altos e
humanos. Se um personagem está em apenas uma das tabelas, as colunas da
outra tabela são preenchidas com <code>NA</code>.</p>
</div>
<div id="exercícios-19" class="section level3 hasAnchor" number="16.2.12">
<h3><span class="header-section-number">16.2.12</span> Exercícios<a href="#exerc%C3%ADcios-19" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1.</strong> Crie uma tabela <code>personagens_altos</code> contendo apenas personagens
com altura superior a 180 cm e uma outra tabela <code>personagens_leves</code>
contendo apenas personagens com massa inferior a 75 kg. Use
<code>left_join()</code> para combinar as duas tabelas com base no nome do
personagem.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="manipulação-de-dados.html#cb282-1" tabindex="-1"></a><span class="co"># Criação dos subconjuntos</span></span>
<span id="cb282-2"><a href="manipulação-de-dados.html#cb282-2" tabindex="-1"></a>personagens_altos <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb282-3"><a href="manipulação-de-dados.html#cb282-3" tabindex="-1"></a>  <span class="fu">filter</span>(height <span class="sc">&gt;</span> <span class="dv">180</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb282-4"><a href="manipulação-de-dados.html#cb282-4" tabindex="-1"></a>  <span class="fu">select</span>(name, height)</span>
<span id="cb282-5"><a href="manipulação-de-dados.html#cb282-5" tabindex="-1"></a></span>
<span id="cb282-6"><a href="manipulação-de-dados.html#cb282-6" tabindex="-1"></a>personagens_leves <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb282-7"><a href="manipulação-de-dados.html#cb282-7" tabindex="-1"></a>  <span class="fu">filter</span>(mass <span class="sc">&lt;</span> <span class="dv">75</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb282-8"><a href="manipulação-de-dados.html#cb282-8" tabindex="-1"></a>  <span class="fu">select</span>(name, mass)</span>
<span id="cb282-9"><a href="manipulação-de-dados.html#cb282-9" tabindex="-1"></a></span>
<span id="cb282-10"><a href="manipulação-de-dados.html#cb282-10" tabindex="-1"></a><span class="co"># Combinação com left_join</span></span>
<span id="cb282-11"><a href="manipulação-de-dados.html#cb282-11" tabindex="-1"></a><span class="fu">left_join</span>(personagens_altos, personagens_leves, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span></code></pre></div>
<p><strong>Dica</strong>: Observe como <code>left_join()</code> mantém todos os personagens altos e
adiciona informações sobre massa apenas para aqueles que também são
leves.</p>
<p><strong>2.</strong> Crie uma tabela <code>personagens_humanos</code> contendo apenas personagens
humanos e uma outra tabela <code>cor_cabelo</code> contendo apenas personagens com
cor de cabelo diferente de <code>NA</code>. Use <code>right_join()</code> para combinar
<code>personagens_humanos</code> e <code>cor_cabelo</code> com base no nome do personagem.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="manipulação-de-dados.html#cb283-1" tabindex="-1"></a><span class="co"># Criação dos subconjuntos</span></span>
<span id="cb283-2"><a href="manipulação-de-dados.html#cb283-2" tabindex="-1"></a>personagens_humanos <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb283-3"><a href="manipulação-de-dados.html#cb283-3" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Human&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb283-4"><a href="manipulação-de-dados.html#cb283-4" tabindex="-1"></a>  <span class="fu">select</span>(name, species)</span>
<span id="cb283-5"><a href="manipulação-de-dados.html#cb283-5" tabindex="-1"></a></span>
<span id="cb283-6"><a href="manipulação-de-dados.html#cb283-6" tabindex="-1"></a>cor_cabelo <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb283-7"><a href="manipulação-de-dados.html#cb283-7" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(hair_color)) <span class="sc">%&gt;%</span> </span>
<span id="cb283-8"><a href="manipulação-de-dados.html#cb283-8" tabindex="-1"></a>  <span class="fu">select</span>(name, hair_color,)</span>
<span id="cb283-9"><a href="manipulação-de-dados.html#cb283-9" tabindex="-1"></a></span>
<span id="cb283-10"><a href="manipulação-de-dados.html#cb283-10" tabindex="-1"></a><span class="co"># Combinação com right_join</span></span>
<span id="cb283-11"><a href="manipulação-de-dados.html#cb283-11" tabindex="-1"></a><span class="fu">right_join</span>(personagens_humanos, cor_cabelo, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span></code></pre></div>
<p><strong>Dica</strong>: Observe como <code>right_join()</code> mantém todos os personagens com
cor de cabelo conhecida e adiciona informações sobre a espécie apenas
para aqueles que também são humanos.</p>
<p><strong>3.</strong> Crie uma tabela <code>especies_personagens</code> contendo apenas
personagens de espécies conhecidas (não <code>NA</code>) e uma outra tabela
<code>cor_olhos</code> contendo apenas personagens com cor de olho conhecida (não
<code>NA</code>). Use <code>full_join()</code> para combinar as duas tabelas com base no nome
do personagem.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="manipulação-de-dados.html#cb284-1" tabindex="-1"></a><span class="co"># Criação dos subconjuntos</span></span>
<span id="cb284-2"><a href="manipulação-de-dados.html#cb284-2" tabindex="-1"></a>especies_personagens <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb284-3"><a href="manipulação-de-dados.html#cb284-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(species)) <span class="sc">%&gt;%</span> </span>
<span id="cb284-4"><a href="manipulação-de-dados.html#cb284-4" tabindex="-1"></a>  <span class="fu">select</span>(name, species)</span>
<span id="cb284-5"><a href="manipulação-de-dados.html#cb284-5" tabindex="-1"></a></span>
<span id="cb284-6"><a href="manipulação-de-dados.html#cb284-6" tabindex="-1"></a>cor_olhos <span class="ot">&lt;-</span> sw <span class="sc">%&gt;%</span> </span>
<span id="cb284-7"><a href="manipulação-de-dados.html#cb284-7" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(eye_color)) <span class="sc">%&gt;%</span> </span>
<span id="cb284-8"><a href="manipulação-de-dados.html#cb284-8" tabindex="-1"></a>  <span class="fu">select</span>(name, eye_color)</span>
<span id="cb284-9"><a href="manipulação-de-dados.html#cb284-9" tabindex="-1"></a></span>
<span id="cb284-10"><a href="manipulação-de-dados.html#cb284-10" tabindex="-1"></a><span class="co"># Combinação com full_join</span></span>
<span id="cb284-11"><a href="manipulação-de-dados.html#cb284-11" tabindex="-1"></a><span class="fu">full_join</span>(especies_personagens, cor_olhos, <span class="at">by =</span> <span class="st">&quot;name&quot;</span>)</span></code></pre></div>
<p><strong>Dica</strong>: <code>full_join()</code> combina todas as informações disponíveis,
preenchendo com NA onde não há correspondências.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="gráficos-r-base.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="o-pacote-ggplot2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["introR.pdf", "introR.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
